"""
Feature Calculator - Mass Production Mode
Auto-generated by feature_mass_producer.py
Total features: 335
"""

import math
import os
import sys
from datetime import datetime
from typing import Dict, List, Optional

_ch1_dir = os.path.dirname(os.path.abspath(__file__))
if _ch1_dir not in sys.path:
    sys.path.insert(0, _ch1_dir)

from channel1_calculators import (
    calc_anomaly,
    calc_concentration,
    calc_concentration_by_category,
    calc_count,
    calc_cross_discrepancy,
    calc_decayed_sum,
    calc_declared_vs_actual,
    calc_deviation,
    calc_distinct_count,
    calc_identity_cluster,
    calc_overlap,
    calc_percentile,
    calc_period_compare,
    calc_proportion,
    calc_proportion_by_category,
    calc_spike,
    calc_trend
)


class FeatureCalculator:
    """Mass-produced feature calculator"""

    def __init__(self, app_category_cache=None, ref_distributions=None):
        self.app_category_cache = app_category_cache or {}
        self.ref_distributions = ref_distributions or {}
        self.gambling_packages = {pkg for pkg, info in self.app_category_cache.items()
                                   if info.get("category") == "gambling"}
        self.loan_packages = {pkg for pkg, info in self.app_category_cache.items()
                               if info.get("category") in ("cash_loan", "fintech_lending")}

    def _get_apply_time(self, data):
        return data.get('applyTime') or data.get('params', {}).get('base', {}).get('applyTime', 0)
    def _get_salary_from_data(self, data):
        try:
            return float(data.get('params', {}).get('base', {}).get('salary', 0))
        except (ValueError, TypeError):
            return 0.0
    def _get_loan_amount_from_data(self, data):
        try:
            pinjaman = data.get('params', {}).get('FDC', {}).get('pinjaman', [])
            amounts = [float(p.get('nilai_pendanaan', 0)) for p in pinjaman if p.get('nilai_pendanaan')]
            return max(amounts) if amounts else 0.0
        except:
            return 0.0
    def _get_inquiry_count_from_data(self, data):
        try:
            stat = data.get('params', {}).get('FDC', {}).get('history_inquiry', {}).get('statistic', {})
            return float(stat.get('30_hari', 0))
        except:
            return 0.0
    def _get_applist_count_from_data(self, data):
        try:
            return float(len(data.get('params', {}).get('appList', [])))
        except:
            return 0.0
    def _get_app_install_pattern_vector(self, data):
        try:
            applist = data.get('params', {}).get('appList', [])
            total = len(applist)
            sys_count = sum(1 for a in applist if a.get('sysApp') == 1)
            return [float(total), float(sys_count), float(total - sys_count)]
        except:
            return [0.0, 0.0, 0.0]
    def _get_loan_pattern_vector(self, data):
        try:
            pinjaman = data.get('params', {}).get('FDC', {}).get('pinjaman', [])
            amounts = [float(p.get('nilai_pendanaan', 0)) for p in pinjaman if p.get('nilai_pendanaan')]
            lenders = set(p.get('id_penyelenggara', '') for p in pinjaman if p.get('id_penyelenggara'))
            total_loans = len(pinjaman)
            max_amt = max(amounts) if amounts else 0
            avg_amt = sum(amounts) / len(amounts) if amounts else 0
            return [float(total_loans), float(max_amt), float(avg_amt), float(len(lenders))]
        except:
            return [0.0, 0.0, 0.0, 0.0]

    def calculate_all(self, data, apply_time=None) -> dict:
        if apply_time is None:
            apply_time = self._get_apply_time(data)
        if apply_time == 0:
            return {}

        apply_dt = datetime.fromtimestamp(apply_time / 1000)

        # cnt_fdciq_3d
        cnt_fdciq_3d = calc_count(data, field_set='fdc_inquiry', window_days=3, apply_time_dt=apply_dt)

        # cnt_fdciq_7d
        cnt_fdciq_7d = calc_count(data, field_set='fdc_inquiry', window_days=7, apply_time_dt=apply_dt)

        # cnt_fdciq_15d
        cnt_fdciq_15d = calc_count(data, field_set='fdc_inquiry', window_days=15, apply_time_dt=apply_dt)

        # cnt_fdciq_30d
        cnt_fdciq_30d = calc_count(data, field_set='fdc_inquiry', window_days=30, apply_time_dt=apply_dt)

        # cnt_fdciq_90d
        cnt_fdciq_90d = calc_count(data, field_set='fdc_inquiry', window_days=90, apply_time_dt=apply_dt)

        # cnt_fdciq_180d
        cnt_fdciq_180d = calc_count(data, field_set='fdc_inquiry', window_days=180, apply_time_dt=apply_dt)

        # cnt_app_7d
        cnt_app_7d = calc_count(data, field_set='applist', window_days=7, apply_time_dt=apply_dt)

        # cnt_app_15d
        cnt_app_15d = calc_count(data, field_set='applist', window_days=15, apply_time_dt=apply_dt)

        # cnt_app_30d
        cnt_app_30d = calc_count(data, field_set='applist', window_days=30, apply_time_dt=apply_dt)

        # cnt_app_60d
        cnt_app_60d = calc_count(data, field_set='applist', window_days=60, apply_time_dt=apply_dt)

        # cnt_app_90d
        cnt_app_90d = calc_count(data, field_set='applist', window_days=90, apply_time_dt=apply_dt)

        # cnt_app_180d
        cnt_app_180d = calc_count(data, field_set='applist', window_days=180, apply_time_dt=apply_dt)

        # cnt_fdcpin_7d
        cnt_fdcpin_7d = calc_count(data, field_set='fdc_pinjaman', window_days=7, apply_time_dt=apply_dt)

        # cnt_fdcpin_15d
        cnt_fdcpin_15d = calc_count(data, field_set='fdc_pinjaman', window_days=15, apply_time_dt=apply_dt)

        # cnt_fdcpin_30d
        cnt_fdcpin_30d = calc_count(data, field_set='fdc_pinjaman', window_days=30, apply_time_dt=apply_dt)

        # cnt_fdcpin_60d
        cnt_fdcpin_60d = calc_count(data, field_set='fdc_pinjaman', window_days=60, apply_time_dt=apply_dt)

        # cnt_fdcpin_90d
        cnt_fdcpin_90d = calc_count(data, field_set='fdc_pinjaman', window_days=90, apply_time_dt=apply_dt)

        # cnt_fdcpin_180d
        cnt_fdcpin_180d = calc_count(data, field_set='fdc_pinjaman', window_days=180, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_o_7d
        cnt_fdcpin_status_pinjaman_o_7d = calc_count(data, field_set='fdc_pinjaman', window_days=7, cond={'status_pinjaman': 'O'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_o_15d
        cnt_fdcpin_status_pinjaman_o_15d = calc_count(data, field_set='fdc_pinjaman', window_days=15, cond={'status_pinjaman': 'O'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_o_30d
        cnt_fdcpin_status_pinjaman_o_30d = calc_count(data, field_set='fdc_pinjaman', window_days=30, cond={'status_pinjaman': 'O'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_o_60d
        cnt_fdcpin_status_pinjaman_o_60d = calc_count(data, field_set='fdc_pinjaman', window_days=60, cond={'status_pinjaman': 'O'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_o_90d
        cnt_fdcpin_status_pinjaman_o_90d = calc_count(data, field_set='fdc_pinjaman', window_days=90, cond={'status_pinjaman': 'O'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_o_180d
        cnt_fdcpin_status_pinjaman_o_180d = calc_count(data, field_set='fdc_pinjaman', window_days=180, cond={'status_pinjaman': 'O'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_l_7d
        cnt_fdcpin_status_pinjaman_l_7d = calc_count(data, field_set='fdc_pinjaman', window_days=7, cond={'status_pinjaman': 'L'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_l_15d
        cnt_fdcpin_status_pinjaman_l_15d = calc_count(data, field_set='fdc_pinjaman', window_days=15, cond={'status_pinjaman': 'L'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_l_30d
        cnt_fdcpin_status_pinjaman_l_30d = calc_count(data, field_set='fdc_pinjaman', window_days=30, cond={'status_pinjaman': 'L'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_l_60d
        cnt_fdcpin_status_pinjaman_l_60d = calc_count(data, field_set='fdc_pinjaman', window_days=60, cond={'status_pinjaman': 'L'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_l_90d
        cnt_fdcpin_status_pinjaman_l_90d = calc_count(data, field_set='fdc_pinjaman', window_days=90, cond={'status_pinjaman': 'L'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_l_180d
        cnt_fdcpin_status_pinjaman_l_180d = calc_count(data, field_set='fdc_pinjaman', window_days=180, cond={'status_pinjaman': 'L'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_w_7d
        cnt_fdcpin_status_pinjaman_w_7d = calc_count(data, field_set='fdc_pinjaman', window_days=7, cond={'status_pinjaman': 'W'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_w_15d
        cnt_fdcpin_status_pinjaman_w_15d = calc_count(data, field_set='fdc_pinjaman', window_days=15, cond={'status_pinjaman': 'W'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_w_30d
        cnt_fdcpin_status_pinjaman_w_30d = calc_count(data, field_set='fdc_pinjaman', window_days=30, cond={'status_pinjaman': 'W'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_w_60d
        cnt_fdcpin_status_pinjaman_w_60d = calc_count(data, field_set='fdc_pinjaman', window_days=60, cond={'status_pinjaman': 'W'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_w_90d
        cnt_fdcpin_status_pinjaman_w_90d = calc_count(data, field_set='fdc_pinjaman', window_days=90, cond={'status_pinjaman': 'W'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_w_180d
        cnt_fdcpin_status_pinjaman_w_180d = calc_count(data, field_set='fdc_pinjaman', window_days=180, cond={'status_pinjaman': 'W'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_f_7d
        cnt_fdcpin_status_pinjaman_f_7d = calc_count(data, field_set='fdc_pinjaman', window_days=7, cond={'status_pinjaman': 'F'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_f_15d
        cnt_fdcpin_status_pinjaman_f_15d = calc_count(data, field_set='fdc_pinjaman', window_days=15, cond={'status_pinjaman': 'F'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_f_30d
        cnt_fdcpin_status_pinjaman_f_30d = calc_count(data, field_set='fdc_pinjaman', window_days=30, cond={'status_pinjaman': 'F'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_f_60d
        cnt_fdcpin_status_pinjaman_f_60d = calc_count(data, field_set='fdc_pinjaman', window_days=60, cond={'status_pinjaman': 'F'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_f_90d
        cnt_fdcpin_status_pinjaman_f_90d = calc_count(data, field_set='fdc_pinjaman', window_days=90, cond={'status_pinjaman': 'F'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_status_pinjaman_f_180d
        cnt_fdcpin_status_pinjaman_f_180d = calc_count(data, field_set='fdc_pinjaman', window_days=180, cond={'status_pinjaman': 'F'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_kualitas_pinjaman_1_7d
        cnt_fdcpin_kualitas_pinjaman_1_7d = calc_count(data, field_set='fdc_pinjaman', window_days=7, cond={'kualitas_pinjaman': '1'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_kualitas_pinjaman_1_15d
        cnt_fdcpin_kualitas_pinjaman_1_15d = calc_count(data, field_set='fdc_pinjaman', window_days=15, cond={'kualitas_pinjaman': '1'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_kualitas_pinjaman_1_30d
        cnt_fdcpin_kualitas_pinjaman_1_30d = calc_count(data, field_set='fdc_pinjaman', window_days=30, cond={'kualitas_pinjaman': '1'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_kualitas_pinjaman_1_60d
        cnt_fdcpin_kualitas_pinjaman_1_60d = calc_count(data, field_set='fdc_pinjaman', window_days=60, cond={'kualitas_pinjaman': '1'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_kualitas_pinjaman_1_90d
        cnt_fdcpin_kualitas_pinjaman_1_90d = calc_count(data, field_set='fdc_pinjaman', window_days=90, cond={'kualitas_pinjaman': '1'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_kualitas_pinjaman_1_180d
        cnt_fdcpin_kualitas_pinjaman_1_180d = calc_count(data, field_set='fdc_pinjaman', window_days=180, cond={'kualitas_pinjaman': '1'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_kualitas_pinjaman_3_7d
        cnt_fdcpin_kualitas_pinjaman_3_7d = calc_count(data, field_set='fdc_pinjaman', window_days=7, cond={'kualitas_pinjaman': '3'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_kualitas_pinjaman_3_15d
        cnt_fdcpin_kualitas_pinjaman_3_15d = calc_count(data, field_set='fdc_pinjaman', window_days=15, cond={'kualitas_pinjaman': '3'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_kualitas_pinjaman_3_30d
        cnt_fdcpin_kualitas_pinjaman_3_30d = calc_count(data, field_set='fdc_pinjaman', window_days=30, cond={'kualitas_pinjaman': '3'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_kualitas_pinjaman_3_60d
        cnt_fdcpin_kualitas_pinjaman_3_60d = calc_count(data, field_set='fdc_pinjaman', window_days=60, cond={'kualitas_pinjaman': '3'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_kualitas_pinjaman_3_90d
        cnt_fdcpin_kualitas_pinjaman_3_90d = calc_count(data, field_set='fdc_pinjaman', window_days=90, cond={'kualitas_pinjaman': '3'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_kualitas_pinjaman_3_180d
        cnt_fdcpin_kualitas_pinjaman_3_180d = calc_count(data, field_set='fdc_pinjaman', window_days=180, cond={'kualitas_pinjaman': '3'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_kualitas_pinjaman_5_7d
        cnt_fdcpin_kualitas_pinjaman_5_7d = calc_count(data, field_set='fdc_pinjaman', window_days=7, cond={'kualitas_pinjaman': '5'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_kualitas_pinjaman_5_15d
        cnt_fdcpin_kualitas_pinjaman_5_15d = calc_count(data, field_set='fdc_pinjaman', window_days=15, cond={'kualitas_pinjaman': '5'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_kualitas_pinjaman_5_30d
        cnt_fdcpin_kualitas_pinjaman_5_30d = calc_count(data, field_set='fdc_pinjaman', window_days=30, cond={'kualitas_pinjaman': '5'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_kualitas_pinjaman_5_60d
        cnt_fdcpin_kualitas_pinjaman_5_60d = calc_count(data, field_set='fdc_pinjaman', window_days=60, cond={'kualitas_pinjaman': '5'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_kualitas_pinjaman_5_90d
        cnt_fdcpin_kualitas_pinjaman_5_90d = calc_count(data, field_set='fdc_pinjaman', window_days=90, cond={'kualitas_pinjaman': '5'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_kualitas_pinjaman_5_180d
        cnt_fdcpin_kualitas_pinjaman_5_180d = calc_count(data, field_set='fdc_pinjaman', window_days=180, cond={'kualitas_pinjaman': '5'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_tipe_pinjaman_multiguna_7d
        cnt_fdcpin_tipe_pinjaman_multiguna_7d = calc_count(data, field_set='fdc_pinjaman', window_days=7, cond={'tipe_pinjaman': 'Multiguna'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_tipe_pinjaman_multiguna_15d
        cnt_fdcpin_tipe_pinjaman_multiguna_15d = calc_count(data, field_set='fdc_pinjaman', window_days=15, cond={'tipe_pinjaman': 'Multiguna'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_tipe_pinjaman_multiguna_30d
        cnt_fdcpin_tipe_pinjaman_multiguna_30d = calc_count(data, field_set='fdc_pinjaman', window_days=30, cond={'tipe_pinjaman': 'Multiguna'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_tipe_pinjaman_multiguna_60d
        cnt_fdcpin_tipe_pinjaman_multiguna_60d = calc_count(data, field_set='fdc_pinjaman', window_days=60, cond={'tipe_pinjaman': 'Multiguna'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_tipe_pinjaman_multiguna_90d
        cnt_fdcpin_tipe_pinjaman_multiguna_90d = calc_count(data, field_set='fdc_pinjaman', window_days=90, cond={'tipe_pinjaman': 'Multiguna'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_tipe_pinjaman_multiguna_180d
        cnt_fdcpin_tipe_pinjaman_multiguna_180d = calc_count(data, field_set='fdc_pinjaman', window_days=180, cond={'tipe_pinjaman': 'Multiguna'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_tipe_pinjaman_produktif_7d
        cnt_fdcpin_tipe_pinjaman_produktif_7d = calc_count(data, field_set='fdc_pinjaman', window_days=7, cond={'tipe_pinjaman': 'Produktif'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_tipe_pinjaman_produktif_15d
        cnt_fdcpin_tipe_pinjaman_produktif_15d = calc_count(data, field_set='fdc_pinjaman', window_days=15, cond={'tipe_pinjaman': 'Produktif'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_tipe_pinjaman_produktif_30d
        cnt_fdcpin_tipe_pinjaman_produktif_30d = calc_count(data, field_set='fdc_pinjaman', window_days=30, cond={'tipe_pinjaman': 'Produktif'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_tipe_pinjaman_produktif_60d
        cnt_fdcpin_tipe_pinjaman_produktif_60d = calc_count(data, field_set='fdc_pinjaman', window_days=60, cond={'tipe_pinjaman': 'Produktif'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_tipe_pinjaman_produktif_90d
        cnt_fdcpin_tipe_pinjaman_produktif_90d = calc_count(data, field_set='fdc_pinjaman', window_days=90, cond={'tipe_pinjaman': 'Produktif'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_tipe_pinjaman_produktif_180d
        cnt_fdcpin_tipe_pinjaman_produktif_180d = calc_count(data, field_set='fdc_pinjaman', window_days=180, cond={'tipe_pinjaman': 'Produktif'}, apply_time_dt=apply_dt)

        # cnt_fdcpin_pendanaan_syariah_true_7d
        cnt_fdcpin_pendanaan_syariah_true_7d = calc_count(data, field_set='fdc_pinjaman', window_days=7, cond={'pendanaan_syariah': True}, apply_time_dt=apply_dt)

        # cnt_fdcpin_pendanaan_syariah_true_15d
        cnt_fdcpin_pendanaan_syariah_true_15d = calc_count(data, field_set='fdc_pinjaman', window_days=15, cond={'pendanaan_syariah': True}, apply_time_dt=apply_dt)

        # cnt_fdcpin_pendanaan_syariah_true_30d
        cnt_fdcpin_pendanaan_syariah_true_30d = calc_count(data, field_set='fdc_pinjaman', window_days=30, cond={'pendanaan_syariah': True}, apply_time_dt=apply_dt)

        # cnt_fdcpin_pendanaan_syariah_true_60d
        cnt_fdcpin_pendanaan_syariah_true_60d = calc_count(data, field_set='fdc_pinjaman', window_days=60, cond={'pendanaan_syariah': True}, apply_time_dt=apply_dt)

        # cnt_fdcpin_pendanaan_syariah_true_90d
        cnt_fdcpin_pendanaan_syariah_true_90d = calc_count(data, field_set='fdc_pinjaman', window_days=90, cond={'pendanaan_syariah': True}, apply_time_dt=apply_dt)

        # cnt_fdcpin_pendanaan_syariah_true_180d
        cnt_fdcpin_pendanaan_syariah_true_180d = calc_count(data, field_set='fdc_pinjaman', window_days=180, cond={'pendanaan_syariah': True}, apply_time_dt=apply_dt)

        # cnt_fdcpin_pendanaan_syariah_false_7d
        cnt_fdcpin_pendanaan_syariah_false_7d = calc_count(data, field_set='fdc_pinjaman', window_days=7, cond={'pendanaan_syariah': False}, apply_time_dt=apply_dt)

        # cnt_fdcpin_pendanaan_syariah_false_15d
        cnt_fdcpin_pendanaan_syariah_false_15d = calc_count(data, field_set='fdc_pinjaman', window_days=15, cond={'pendanaan_syariah': False}, apply_time_dt=apply_dt)

        # cnt_fdcpin_pendanaan_syariah_false_30d
        cnt_fdcpin_pendanaan_syariah_false_30d = calc_count(data, field_set='fdc_pinjaman', window_days=30, cond={'pendanaan_syariah': False}, apply_time_dt=apply_dt)

        # cnt_fdcpin_pendanaan_syariah_false_60d
        cnt_fdcpin_pendanaan_syariah_false_60d = calc_count(data, field_set='fdc_pinjaman', window_days=60, cond={'pendanaan_syariah': False}, apply_time_dt=apply_dt)

        # cnt_fdcpin_pendanaan_syariah_false_90d
        cnt_fdcpin_pendanaan_syariah_false_90d = calc_count(data, field_set='fdc_pinjaman', window_days=90, cond={'pendanaan_syariah': False}, apply_time_dt=apply_dt)

        # cnt_fdcpin_pendanaan_syariah_false_180d
        cnt_fdcpin_pendanaan_syariah_false_180d = calc_count(data, field_set='fdc_pinjaman', window_days=180, cond={'pendanaan_syariah': False}, apply_time_dt=apply_dt)

        # uniq_fdciq_hitby_7d
        uniq_fdciq_hitby_7d = calc_distinct_count(data, field_set='fdc_inquiry', window_days=7, dedup_field='hit_by', apply_time_dt=apply_dt)

        # uniq_fdciq_hitby_15d
        uniq_fdciq_hitby_15d = calc_distinct_count(data, field_set='fdc_inquiry', window_days=15, dedup_field='hit_by', apply_time_dt=apply_dt)

        # uniq_fdciq_hitby_30d
        uniq_fdciq_hitby_30d = calc_distinct_count(data, field_set='fdc_inquiry', window_days=30, dedup_field='hit_by', apply_time_dt=apply_dt)

        # uniq_fdciq_hitby_60d
        uniq_fdciq_hitby_60d = calc_distinct_count(data, field_set='fdc_inquiry', window_days=60, dedup_field='hit_by', apply_time_dt=apply_dt)

        # uniq_fdciq_hitby_90d
        uniq_fdciq_hitby_90d = calc_distinct_count(data, field_set='fdc_inquiry', window_days=90, dedup_field='hit_by', apply_time_dt=apply_dt)

        # uniq_fdciq_hitby_180d
        uniq_fdciq_hitby_180d = calc_distinct_count(data, field_set='fdc_inquiry', window_days=180, dedup_field='hit_by', apply_time_dt=apply_dt)

        # uniq_fdcpin_lender_30d
        uniq_fdcpin_lender_30d = calc_distinct_count(data, field_set='fdc_pinjaman', window_days=30, dedup_field='id_penyelenggara', apply_time_dt=apply_dt)

        # uniq_fdcpin_lender_60d
        uniq_fdcpin_lender_60d = calc_distinct_count(data, field_set='fdc_pinjaman', window_days=60, dedup_field='id_penyelenggara', apply_time_dt=apply_dt)

        # uniq_fdcpin_lender_90d
        uniq_fdcpin_lender_90d = calc_distinct_count(data, field_set='fdc_pinjaman', window_days=90, dedup_field='id_penyelenggara', apply_time_dt=apply_dt)

        # uniq_fdcpin_lender_180d
        uniq_fdcpin_lender_180d = calc_distinct_count(data, field_set='fdc_pinjaman', window_days=180, dedup_field='id_penyelenggara', apply_time_dt=apply_dt)

        # uniq_fdcpin_loan_type_30d
        uniq_fdcpin_loan_type_30d = calc_distinct_count(data, field_set='fdc_pinjaman', window_days=30, dedup_field='tipe_pinjaman', apply_time_dt=apply_dt)

        # uniq_fdcpin_loan_type_60d
        uniq_fdcpin_loan_type_60d = calc_distinct_count(data, field_set='fdc_pinjaman', window_days=60, dedup_field='tipe_pinjaman', apply_time_dt=apply_dt)

        # uniq_fdcpin_loan_type_90d
        uniq_fdcpin_loan_type_90d = calc_distinct_count(data, field_set='fdc_pinjaman', window_days=90, dedup_field='tipe_pinjaman', apply_time_dt=apply_dt)

        # uniq_fdcpin_loan_type_180d
        uniq_fdcpin_loan_type_180d = calc_distinct_count(data, field_set='fdc_pinjaman', window_days=180, dedup_field='tipe_pinjaman', apply_time_dt=apply_dt)

        # uniq_fdcpin_loan_status_30d
        uniq_fdcpin_loan_status_30d = calc_distinct_count(data, field_set='fdc_pinjaman', window_days=30, dedup_field='status_pinjaman', apply_time_dt=apply_dt)

        # uniq_fdcpin_loan_status_60d
        uniq_fdcpin_loan_status_60d = calc_distinct_count(data, field_set='fdc_pinjaman', window_days=60, dedup_field='status_pinjaman', apply_time_dt=apply_dt)

        # uniq_fdcpin_loan_status_90d
        uniq_fdcpin_loan_status_90d = calc_distinct_count(data, field_set='fdc_pinjaman', window_days=90, dedup_field='status_pinjaman', apply_time_dt=apply_dt)

        # uniq_fdcpin_loan_status_180d
        uniq_fdcpin_loan_status_180d = calc_distinct_count(data, field_set='fdc_pinjaman', window_days=180, dedup_field='status_pinjaman', apply_time_dt=apply_dt)

        # decay_fdcpin_amt_30d_r005
        decay_fdcpin_amt_30d_r005 = calc_decayed_sum(data, field_set='fdc_pinjaman', window_days=30, decay_func='exponential', decay_rate=0.05, value_field='nilai_pendanaan', apply_time_dt=apply_dt)

        # decay_fdcpin_amt_60d_r005
        decay_fdcpin_amt_60d_r005 = calc_decayed_sum(data, field_set='fdc_pinjaman', window_days=60, decay_func='exponential', decay_rate=0.05, value_field='nilai_pendanaan', apply_time_dt=apply_dt)

        # decay_fdcpin_amt_90d_r005
        decay_fdcpin_amt_90d_r005 = calc_decayed_sum(data, field_set='fdc_pinjaman', window_days=90, decay_func='exponential', decay_rate=0.05, value_field='nilai_pendanaan', apply_time_dt=apply_dt)

        # decay_fdcpin_amt_180d_r005
        decay_fdcpin_amt_180d_r005 = calc_decayed_sum(data, field_set='fdc_pinjaman', window_days=180, decay_func='exponential', decay_rate=0.05, value_field='nilai_pendanaan', apply_time_dt=apply_dt)

        # decay_fdcpin_amt_30d_r002
        decay_fdcpin_amt_30d_r002 = calc_decayed_sum(data, field_set='fdc_pinjaman', window_days=30, decay_func='exponential', decay_rate=0.02, value_field='nilai_pendanaan', apply_time_dt=apply_dt)

        # decay_fdcpin_amt_60d_r002
        decay_fdcpin_amt_60d_r002 = calc_decayed_sum(data, field_set='fdc_pinjaman', window_days=60, decay_func='exponential', decay_rate=0.02, value_field='nilai_pendanaan', apply_time_dt=apply_dt)

        # decay_fdcpin_amt_90d_r002
        decay_fdcpin_amt_90d_r002 = calc_decayed_sum(data, field_set='fdc_pinjaman', window_days=90, decay_func='exponential', decay_rate=0.02, value_field='nilai_pendanaan', apply_time_dt=apply_dt)

        # decay_fdcpin_amt_180d_r002
        decay_fdcpin_amt_180d_r002 = calc_decayed_sum(data, field_set='fdc_pinjaman', window_days=180, decay_func='exponential', decay_rate=0.02, value_field='nilai_pendanaan', apply_time_dt=apply_dt)

        # decay_fdcpin_amt_30d_r01
        decay_fdcpin_amt_30d_r01 = calc_decayed_sum(data, field_set='fdc_pinjaman', window_days=30, decay_func='exponential', decay_rate=0.1, value_field='nilai_pendanaan', apply_time_dt=apply_dt)

        # decay_fdcpin_amt_60d_r01
        decay_fdcpin_amt_60d_r01 = calc_decayed_sum(data, field_set='fdc_pinjaman', window_days=60, decay_func='exponential', decay_rate=0.1, value_field='nilai_pendanaan', apply_time_dt=apply_dt)

        # decay_fdcpin_amt_90d_r01
        decay_fdcpin_amt_90d_r01 = calc_decayed_sum(data, field_set='fdc_pinjaman', window_days=90, decay_func='exponential', decay_rate=0.1, value_field='nilai_pendanaan', apply_time_dt=apply_dt)

        # decay_fdcpin_amt_180d_r01
        decay_fdcpin_amt_180d_r01 = calc_decayed_sum(data, field_set='fdc_pinjaman', window_days=180, decay_func='exponential', decay_rate=0.1, value_field='nilai_pendanaan', apply_time_dt=apply_dt)

        # decay_fdcpin_amt_30d_r05
        decay_fdcpin_amt_30d_r05 = calc_decayed_sum(data, field_set='fdc_pinjaman', window_days=30, decay_func='linear', decay_rate=0.5, value_field='nilai_pendanaan', apply_time_dt=apply_dt)

        # decay_fdcpin_amt_60d_r05
        decay_fdcpin_amt_60d_r05 = calc_decayed_sum(data, field_set='fdc_pinjaman', window_days=60, decay_func='linear', decay_rate=0.5, value_field='nilai_pendanaan', apply_time_dt=apply_dt)

        # decay_fdcpin_amt_90d_r05
        decay_fdcpin_amt_90d_r05 = calc_decayed_sum(data, field_set='fdc_pinjaman', window_days=90, decay_func='linear', decay_rate=0.5, value_field='nilai_pendanaan', apply_time_dt=apply_dt)

        # decay_fdcpin_amt_180d_r05
        decay_fdcpin_amt_180d_r05 = calc_decayed_sum(data, field_set='fdc_pinjaman', window_days=180, decay_func='linear', decay_rate=0.5, value_field='nilai_pendanaan', apply_time_dt=apply_dt)

        # prop_app_gambling_7d
        prop_app_gambling_7d = calc_proportion_by_category(data, window_days=7, allowed_categories={'gambling'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_gambling_30d
        prop_app_gambling_30d = calc_proportion_by_category(data, window_days=30, allowed_categories={'gambling'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_gambling_60d
        prop_app_gambling_60d = calc_proportion_by_category(data, window_days=60, allowed_categories={'gambling'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_gambling_90d
        prop_app_gambling_90d = calc_proportion_by_category(data, window_days=90, allowed_categories={'gambling'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_cash_loan_7d
        prop_app_cash_loan_7d = calc_proportion_by_category(data, window_days=7, allowed_categories={'cash_loan'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_cash_loan_30d
        prop_app_cash_loan_30d = calc_proportion_by_category(data, window_days=30, allowed_categories={'cash_loan'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_cash_loan_60d
        prop_app_cash_loan_60d = calc_proportion_by_category(data, window_days=60, allowed_categories={'cash_loan'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_cash_loan_90d
        prop_app_cash_loan_90d = calc_proportion_by_category(data, window_days=90, allowed_categories={'cash_loan'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_fintech_lending_7d
        prop_app_fintech_lending_7d = calc_proportion_by_category(data, window_days=7, allowed_categories={'fintech_lending'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_fintech_lending_30d
        prop_app_fintech_lending_30d = calc_proportion_by_category(data, window_days=30, allowed_categories={'fintech_lending'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_fintech_lending_60d
        prop_app_fintech_lending_60d = calc_proportion_by_category(data, window_days=60, allowed_categories={'fintech_lending'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_fintech_lending_90d
        prop_app_fintech_lending_90d = calc_proportion_by_category(data, window_days=90, allowed_categories={'fintech_lending'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_fake_gps_7d
        prop_app_fake_gps_7d = calc_proportion_by_category(data, window_days=7, allowed_categories={'fake_gps'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_fake_gps_30d
        prop_app_fake_gps_30d = calc_proportion_by_category(data, window_days=30, allowed_categories={'fake_gps'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_fake_gps_60d
        prop_app_fake_gps_60d = calc_proportion_by_category(data, window_days=60, allowed_categories={'fake_gps'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_fake_gps_90d
        prop_app_fake_gps_90d = calc_proportion_by_category(data, window_days=90, allowed_categories={'fake_gps'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_clone_app_7d
        prop_app_clone_app_7d = calc_proportion_by_category(data, window_days=7, allowed_categories={'clone_app'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_clone_app_30d
        prop_app_clone_app_30d = calc_proportion_by_category(data, window_days=30, allowed_categories={'clone_app'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_clone_app_60d
        prop_app_clone_app_60d = calc_proportion_by_category(data, window_days=60, allowed_categories={'clone_app'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_clone_app_90d
        prop_app_clone_app_90d = calc_proportion_by_category(data, window_days=90, allowed_categories={'clone_app'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_banking_7d
        prop_app_banking_7d = calc_proportion_by_category(data, window_days=7, allowed_categories={'banking'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_banking_30d
        prop_app_banking_30d = calc_proportion_by_category(data, window_days=30, allowed_categories={'banking'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_banking_60d
        prop_app_banking_60d = calc_proportion_by_category(data, window_days=60, allowed_categories={'banking'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_banking_90d
        prop_app_banking_90d = calc_proportion_by_category(data, window_days=90, allowed_categories={'banking'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_ewallet_7d
        prop_app_ewallet_7d = calc_proportion_by_category(data, window_days=7, allowed_categories={'ewallet'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_ewallet_30d
        prop_app_ewallet_30d = calc_proportion_by_category(data, window_days=30, allowed_categories={'ewallet'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_ewallet_60d
        prop_app_ewallet_60d = calc_proportion_by_category(data, window_days=60, allowed_categories={'ewallet'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_ewallet_90d
        prop_app_ewallet_90d = calc_proportion_by_category(data, window_days=90, allowed_categories={'ewallet'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_cash_loan_fintech_lending_7d
        prop_app_cash_loan_fintech_lending_7d = calc_proportion_by_category(data, window_days=7, allowed_categories={'fintech_lending', 'cash_loan'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_cash_loan_fintech_lending_30d
        prop_app_cash_loan_fintech_lending_30d = calc_proportion_by_category(data, window_days=30, allowed_categories={'fintech_lending', 'cash_loan'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_cash_loan_fintech_lending_60d
        prop_app_cash_loan_fintech_lending_60d = calc_proportion_by_category(data, window_days=60, allowed_categories={'fintech_lending', 'cash_loan'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_cash_loan_fintech_lending_90d
        prop_app_cash_loan_fintech_lending_90d = calc_proportion_by_category(data, window_days=90, allowed_categories={'fintech_lending', 'cash_loan'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_gambling_cash_loan_fintech_lending_7d
        prop_app_gambling_cash_loan_fintech_lending_7d = calc_proportion_by_category(data, window_days=7, allowed_categories={'fintech_lending', 'gambling', 'cash_loan'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_gambling_cash_loan_fintech_lending_30d
        prop_app_gambling_cash_loan_fintech_lending_30d = calc_proportion_by_category(data, window_days=30, allowed_categories={'fintech_lending', 'gambling', 'cash_loan'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_gambling_cash_loan_fintech_lending_60d
        prop_app_gambling_cash_loan_fintech_lending_60d = calc_proportion_by_category(data, window_days=60, allowed_categories={'fintech_lending', 'gambling', 'cash_loan'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_gambling_cash_loan_fintech_lending_90d
        prop_app_gambling_cash_loan_fintech_lending_90d = calc_proportion_by_category(data, window_days=90, allowed_categories={'fintech_lending', 'gambling', 'cash_loan'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_shopping_food_delivery_7d
        prop_app_shopping_food_delivery_7d = calc_proportion_by_category(data, window_days=7, allowed_categories={'food_delivery', 'shopping'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_shopping_food_delivery_30d
        prop_app_shopping_food_delivery_30d = calc_proportion_by_category(data, window_days=30, allowed_categories={'food_delivery', 'shopping'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_shopping_food_delivery_60d
        prop_app_shopping_food_delivery_60d = calc_proportion_by_category(data, window_days=60, allowed_categories={'food_delivery', 'shopping'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_app_shopping_food_delivery_90d
        prop_app_shopping_food_delivery_90d = calc_proportion_by_category(data, window_days=90, allowed_categories={'food_delivery', 'shopping'}, category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # prop_fdcpin_kualitas_pinjaman_1_30d
        prop_fdcpin_kualitas_pinjaman_1_30d = calc_proportion(data, window_days=30, source='fdc_pinjaman', target_cond={'kualitas_pinjaman': '1'}, apply_time_dt=apply_dt)

        # prop_fdcpin_kualitas_pinjaman_1_60d
        prop_fdcpin_kualitas_pinjaman_1_60d = calc_proportion(data, window_days=60, source='fdc_pinjaman', target_cond={'kualitas_pinjaman': '1'}, apply_time_dt=apply_dt)

        # prop_fdcpin_kualitas_pinjaman_1_90d
        prop_fdcpin_kualitas_pinjaman_1_90d = calc_proportion(data, window_days=90, source='fdc_pinjaman', target_cond={'kualitas_pinjaman': '1'}, apply_time_dt=apply_dt)

        # prop_fdcpin_kualitas_pinjaman_1_180d
        prop_fdcpin_kualitas_pinjaman_1_180d = calc_proportion(data, window_days=180, source='fdc_pinjaman', target_cond={'kualitas_pinjaman': '1'}, apply_time_dt=apply_dt)

        # prop_fdcpin_kualitas_pinjaman_3_30d
        prop_fdcpin_kualitas_pinjaman_3_30d = calc_proportion(data, window_days=30, source='fdc_pinjaman', target_cond={'kualitas_pinjaman': '3'}, apply_time_dt=apply_dt)

        # prop_fdcpin_kualitas_pinjaman_3_60d
        prop_fdcpin_kualitas_pinjaman_3_60d = calc_proportion(data, window_days=60, source='fdc_pinjaman', target_cond={'kualitas_pinjaman': '3'}, apply_time_dt=apply_dt)

        # prop_fdcpin_kualitas_pinjaman_3_90d
        prop_fdcpin_kualitas_pinjaman_3_90d = calc_proportion(data, window_days=90, source='fdc_pinjaman', target_cond={'kualitas_pinjaman': '3'}, apply_time_dt=apply_dt)

        # prop_fdcpin_kualitas_pinjaman_3_180d
        prop_fdcpin_kualitas_pinjaman_3_180d = calc_proportion(data, window_days=180, source='fdc_pinjaman', target_cond={'kualitas_pinjaman': '3'}, apply_time_dt=apply_dt)

        # prop_fdcpin_kualitas_pinjaman_5_30d
        prop_fdcpin_kualitas_pinjaman_5_30d = calc_proportion(data, window_days=30, source='fdc_pinjaman', target_cond={'kualitas_pinjaman': '5'}, apply_time_dt=apply_dt)

        # prop_fdcpin_kualitas_pinjaman_5_60d
        prop_fdcpin_kualitas_pinjaman_5_60d = calc_proportion(data, window_days=60, source='fdc_pinjaman', target_cond={'kualitas_pinjaman': '5'}, apply_time_dt=apply_dt)

        # prop_fdcpin_kualitas_pinjaman_5_90d
        prop_fdcpin_kualitas_pinjaman_5_90d = calc_proportion(data, window_days=90, source='fdc_pinjaman', target_cond={'kualitas_pinjaman': '5'}, apply_time_dt=apply_dt)

        # prop_fdcpin_kualitas_pinjaman_5_180d
        prop_fdcpin_kualitas_pinjaman_5_180d = calc_proportion(data, window_days=180, source='fdc_pinjaman', target_cond={'kualitas_pinjaman': '5'}, apply_time_dt=apply_dt)

        # prop_fdcpin_status_pinjaman_o_30d
        prop_fdcpin_status_pinjaman_o_30d = calc_proportion(data, window_days=30, source='fdc_pinjaman', target_cond={'status_pinjaman': 'O'}, apply_time_dt=apply_dt)

        # prop_fdcpin_status_pinjaman_o_60d
        prop_fdcpin_status_pinjaman_o_60d = calc_proportion(data, window_days=60, source='fdc_pinjaman', target_cond={'status_pinjaman': 'O'}, apply_time_dt=apply_dt)

        # prop_fdcpin_status_pinjaman_o_90d
        prop_fdcpin_status_pinjaman_o_90d = calc_proportion(data, window_days=90, source='fdc_pinjaman', target_cond={'status_pinjaman': 'O'}, apply_time_dt=apply_dt)

        # prop_fdcpin_status_pinjaman_o_180d
        prop_fdcpin_status_pinjaman_o_180d = calc_proportion(data, window_days=180, source='fdc_pinjaman', target_cond={'status_pinjaman': 'O'}, apply_time_dt=apply_dt)

        # prop_fdcpin_status_pinjaman_l_30d
        prop_fdcpin_status_pinjaman_l_30d = calc_proportion(data, window_days=30, source='fdc_pinjaman', target_cond={'status_pinjaman': 'L'}, apply_time_dt=apply_dt)

        # prop_fdcpin_status_pinjaman_l_60d
        prop_fdcpin_status_pinjaman_l_60d = calc_proportion(data, window_days=60, source='fdc_pinjaman', target_cond={'status_pinjaman': 'L'}, apply_time_dt=apply_dt)

        # prop_fdcpin_status_pinjaman_l_90d
        prop_fdcpin_status_pinjaman_l_90d = calc_proportion(data, window_days=90, source='fdc_pinjaman', target_cond={'status_pinjaman': 'L'}, apply_time_dt=apply_dt)

        # prop_fdcpin_status_pinjaman_l_180d
        prop_fdcpin_status_pinjaman_l_180d = calc_proportion(data, window_days=180, source='fdc_pinjaman', target_cond={'status_pinjaman': 'L'}, apply_time_dt=apply_dt)

        # prop_fdcpin_tipe_pinjaman_multiguna_30d
        prop_fdcpin_tipe_pinjaman_multiguna_30d = calc_proportion(data, window_days=30, source='fdc_pinjaman', target_cond={'tipe_pinjaman': 'Multiguna'}, apply_time_dt=apply_dt)

        # prop_fdcpin_tipe_pinjaman_multiguna_60d
        prop_fdcpin_tipe_pinjaman_multiguna_60d = calc_proportion(data, window_days=60, source='fdc_pinjaman', target_cond={'tipe_pinjaman': 'Multiguna'}, apply_time_dt=apply_dt)

        # prop_fdcpin_tipe_pinjaman_multiguna_90d
        prop_fdcpin_tipe_pinjaman_multiguna_90d = calc_proportion(data, window_days=90, source='fdc_pinjaman', target_cond={'tipe_pinjaman': 'Multiguna'}, apply_time_dt=apply_dt)

        # prop_fdcpin_tipe_pinjaman_multiguna_180d
        prop_fdcpin_tipe_pinjaman_multiguna_180d = calc_proportion(data, window_days=180, source='fdc_pinjaman', target_cond={'tipe_pinjaman': 'Multiguna'}, apply_time_dt=apply_dt)

        # prop_fdcpin_tipe_pinjaman_produktif_30d
        prop_fdcpin_tipe_pinjaman_produktif_30d = calc_proportion(data, window_days=30, source='fdc_pinjaman', target_cond={'tipe_pinjaman': 'Produktif'}, apply_time_dt=apply_dt)

        # prop_fdcpin_tipe_pinjaman_produktif_60d
        prop_fdcpin_tipe_pinjaman_produktif_60d = calc_proportion(data, window_days=60, source='fdc_pinjaman', target_cond={'tipe_pinjaman': 'Produktif'}, apply_time_dt=apply_dt)

        # prop_fdcpin_tipe_pinjaman_produktif_90d
        prop_fdcpin_tipe_pinjaman_produktif_90d = calc_proportion(data, window_days=90, source='fdc_pinjaman', target_cond={'tipe_pinjaman': 'Produktif'}, apply_time_dt=apply_dt)

        # prop_fdcpin_tipe_pinjaman_produktif_180d
        prop_fdcpin_tipe_pinjaman_produktif_180d = calc_proportion(data, window_days=180, source='fdc_pinjaman', target_cond={'tipe_pinjaman': 'Produktif'}, apply_time_dt=apply_dt)

        # prop_fdcpin_pendanaan_syariah_true_30d
        prop_fdcpin_pendanaan_syariah_true_30d = calc_proportion(data, window_days=30, source='fdc_pinjaman', target_cond={'pendanaan_syariah': True}, apply_time_dt=apply_dt)

        # prop_fdcpin_pendanaan_syariah_true_60d
        prop_fdcpin_pendanaan_syariah_true_60d = calc_proportion(data, window_days=60, source='fdc_pinjaman', target_cond={'pendanaan_syariah': True}, apply_time_dt=apply_dt)

        # prop_fdcpin_pendanaan_syariah_true_90d
        prop_fdcpin_pendanaan_syariah_true_90d = calc_proportion(data, window_days=90, source='fdc_pinjaman', target_cond={'pendanaan_syariah': True}, apply_time_dt=apply_dt)

        # prop_fdcpin_pendanaan_syariah_true_180d
        prop_fdcpin_pendanaan_syariah_true_180d = calc_proportion(data, window_days=180, source='fdc_pinjaman', target_cond={'pendanaan_syariah': True}, apply_time_dt=apply_dt)

        # prop_fdcpin_pendanaan_syariah_false_30d
        prop_fdcpin_pendanaan_syariah_false_30d = calc_proportion(data, window_days=30, source='fdc_pinjaman', target_cond={'pendanaan_syariah': False}, apply_time_dt=apply_dt)

        # prop_fdcpin_pendanaan_syariah_false_60d
        prop_fdcpin_pendanaan_syariah_false_60d = calc_proportion(data, window_days=60, source='fdc_pinjaman', target_cond={'pendanaan_syariah': False}, apply_time_dt=apply_dt)

        # prop_fdcpin_pendanaan_syariah_false_90d
        prop_fdcpin_pendanaan_syariah_false_90d = calc_proportion(data, window_days=90, source='fdc_pinjaman', target_cond={'pendanaan_syariah': False}, apply_time_dt=apply_dt)

        # prop_fdcpin_pendanaan_syariah_false_180d
        prop_fdcpin_pendanaan_syariah_false_180d = calc_proportion(data, window_days=180, source='fdc_pinjaman', target_cond={'pendanaan_syariah': False}, apply_time_dt=apply_dt)

        # conc_fdcpin_penyelenggara_gini_30d
        conc_fdcpin_penyelenggara_gini_30d = calc_concentration(data, window_days=30, method='gini', field_set='fdc_pinjaman', category_field='id_penyelenggara', apply_time_dt=apply_dt)

        # conc_fdcpin_penyelenggara_gini_60d
        conc_fdcpin_penyelenggara_gini_60d = calc_concentration(data, window_days=60, method='gini', field_set='fdc_pinjaman', category_field='id_penyelenggara', apply_time_dt=apply_dt)

        # conc_fdcpin_penyelenggara_gini_90d
        conc_fdcpin_penyelenggara_gini_90d = calc_concentration(data, window_days=90, method='gini', field_set='fdc_pinjaman', category_field='id_penyelenggara', apply_time_dt=apply_dt)

        # conc_fdcpin_penyelenggara_gini_180d
        conc_fdcpin_penyelenggara_gini_180d = calc_concentration(data, window_days=180, method='gini', field_set='fdc_pinjaman', category_field='id_penyelenggara', apply_time_dt=apply_dt)

        # conc_fdcpin_pinjaman_gini_30d
        conc_fdcpin_pinjaman_gini_30d = calc_concentration(data, window_days=30, method='gini', field_set='fdc_pinjaman', category_field='tipe_pinjaman', apply_time_dt=apply_dt)

        # conc_fdcpin_pinjaman_gini_60d
        conc_fdcpin_pinjaman_gini_60d = calc_concentration(data, window_days=60, method='gini', field_set='fdc_pinjaman', category_field='tipe_pinjaman', apply_time_dt=apply_dt)

        # conc_fdcpin_pinjaman_gini_90d
        conc_fdcpin_pinjaman_gini_90d = calc_concentration(data, window_days=90, method='gini', field_set='fdc_pinjaman', category_field='tipe_pinjaman', apply_time_dt=apply_dt)

        # conc_fdcpin_pinjaman_gini_180d
        conc_fdcpin_pinjaman_gini_180d = calc_concentration(data, window_days=180, method='gini', field_set='fdc_pinjaman', category_field='tipe_pinjaman', apply_time_dt=apply_dt)

        # conc_fdcpin_penyelenggara_entropy_30d
        conc_fdcpin_penyelenggara_entropy_30d = calc_concentration(data, window_days=30, method='entropy', field_set='fdc_pinjaman', category_field='id_penyelenggara', apply_time_dt=apply_dt)

        # conc_fdcpin_penyelenggara_entropy_60d
        conc_fdcpin_penyelenggara_entropy_60d = calc_concentration(data, window_days=60, method='entropy', field_set='fdc_pinjaman', category_field='id_penyelenggara', apply_time_dt=apply_dt)

        # conc_fdcpin_penyelenggara_entropy_90d
        conc_fdcpin_penyelenggara_entropy_90d = calc_concentration(data, window_days=90, method='entropy', field_set='fdc_pinjaman', category_field='id_penyelenggara', apply_time_dt=apply_dt)

        # conc_fdcpin_penyelenggara_entropy_180d
        conc_fdcpin_penyelenggara_entropy_180d = calc_concentration(data, window_days=180, method='entropy', field_set='fdc_pinjaman', category_field='id_penyelenggara', apply_time_dt=apply_dt)

        # conc_fdcpin_pinjaman_entropy_30d
        conc_fdcpin_pinjaman_entropy_30d = calc_concentration(data, window_days=30, method='entropy', field_set='fdc_pinjaman', category_field='tipe_pinjaman', apply_time_dt=apply_dt)

        # conc_fdcpin_pinjaman_entropy_60d
        conc_fdcpin_pinjaman_entropy_60d = calc_concentration(data, window_days=60, method='entropy', field_set='fdc_pinjaman', category_field='tipe_pinjaman', apply_time_dt=apply_dt)

        # conc_fdcpin_pinjaman_entropy_90d
        conc_fdcpin_pinjaman_entropy_90d = calc_concentration(data, window_days=90, method='entropy', field_set='fdc_pinjaman', category_field='tipe_pinjaman', apply_time_dt=apply_dt)

        # conc_fdcpin_pinjaman_entropy_180d
        conc_fdcpin_pinjaman_entropy_180d = calc_concentration(data, window_days=180, method='entropy', field_set='fdc_pinjaman', category_field='tipe_pinjaman', apply_time_dt=apply_dt)

        # conc_fdcpin_penyelenggara_cv_30d
        conc_fdcpin_penyelenggara_cv_30d = calc_concentration(data, window_days=30, method='cv', field_set='fdc_pinjaman', category_field='id_penyelenggara', apply_time_dt=apply_dt)

        # conc_fdcpin_penyelenggara_cv_60d
        conc_fdcpin_penyelenggara_cv_60d = calc_concentration(data, window_days=60, method='cv', field_set='fdc_pinjaman', category_field='id_penyelenggara', apply_time_dt=apply_dt)

        # conc_fdcpin_penyelenggara_cv_90d
        conc_fdcpin_penyelenggara_cv_90d = calc_concentration(data, window_days=90, method='cv', field_set='fdc_pinjaman', category_field='id_penyelenggara', apply_time_dt=apply_dt)

        # conc_fdcpin_penyelenggara_cv_180d
        conc_fdcpin_penyelenggara_cv_180d = calc_concentration(data, window_days=180, method='cv', field_set='fdc_pinjaman', category_field='id_penyelenggara', apply_time_dt=apply_dt)

        # conc_fdcpin_pinjaman_cv_30d
        conc_fdcpin_pinjaman_cv_30d = calc_concentration(data, window_days=30, method='cv', field_set='fdc_pinjaman', category_field='tipe_pinjaman', apply_time_dt=apply_dt)

        # conc_fdcpin_pinjaman_cv_60d
        conc_fdcpin_pinjaman_cv_60d = calc_concentration(data, window_days=60, method='cv', field_set='fdc_pinjaman', category_field='tipe_pinjaman', apply_time_dt=apply_dt)

        # conc_fdcpin_pinjaman_cv_90d
        conc_fdcpin_pinjaman_cv_90d = calc_concentration(data, window_days=90, method='cv', field_set='fdc_pinjaman', category_field='tipe_pinjaman', apply_time_dt=apply_dt)

        # conc_fdcpin_pinjaman_cv_180d
        conc_fdcpin_pinjaman_cv_180d = calc_concentration(data, window_days=180, method='cv', field_set='fdc_pinjaman', category_field='tipe_pinjaman', apply_time_dt=apply_dt)

        # conc_app_cat_entropy_30d
        conc_app_cat_entropy_30d = calc_concentration_by_category(data, window_days=30, method='entropy', category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # conc_app_cat_entropy_60d
        conc_app_cat_entropy_60d = calc_concentration_by_category(data, window_days=60, method='entropy', category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # conc_app_cat_entropy_90d
        conc_app_cat_entropy_90d = calc_concentration_by_category(data, window_days=90, method='entropy', category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # conc_app_cat_gini_30d
        conc_app_cat_gini_30d = calc_concentration_by_category(data, window_days=30, method='gini', category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # conc_app_cat_gini_60d
        conc_app_cat_gini_60d = calc_concentration_by_category(data, window_days=60, method='gini', category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # conc_app_cat_gini_90d
        conc_app_cat_gini_90d = calc_concentration_by_category(data, window_days=90, method='gini', category_cache=self.app_category_cache, apply_time_dt=apply_dt)

        # ovlap_app_fdc_7d
        ovlap_app_fdc_7d = calc_overlap(data, source_a='applist', field_a='packageX', source_b='fdc_pinjaman', field_b='id_penyelenggara', window_days=7, apply_time_dt=apply_dt)

        # ovlap_app_fdc_30d
        ovlap_app_fdc_30d = calc_overlap(data, source_a='applist', field_a='packageX', source_b='fdc_pinjaman', field_b='id_penyelenggara', window_days=30, apply_time_dt=apply_dt)

        # ovlap_app_fdc_60d
        ovlap_app_fdc_60d = calc_overlap(data, source_a='applist', field_a='packageX', source_b='fdc_pinjaman', field_b='id_penyelenggara', window_days=60, apply_time_dt=apply_dt)

        # ovlap_app_fdc_90d
        ovlap_app_fdc_90d = calc_overlap(data, source_a='applist', field_a='packageX', source_b='fdc_pinjaman', field_b='id_penyelenggara', window_days=90, apply_time_dt=apply_dt)

        # perc_fdciq_3v7d
        perc_fdciq_3v7d = calc_period_compare(data, field_set='fdc_inquiry', short_window=3, long_window=7, apply_time_dt=apply_dt)

        # perc_fdciq_7v30d
        perc_fdciq_7v30d = calc_period_compare(data, field_set='fdc_inquiry', short_window=7, long_window=30, apply_time_dt=apply_dt)

        # perc_fdciq_15v90d
        perc_fdciq_15v90d = calc_period_compare(data, field_set='fdc_inquiry', short_window=15, long_window=90, apply_time_dt=apply_dt)

        # perc_fdcpin_7v30d
        perc_fdcpin_7v30d = calc_period_compare(data, field_set='fdc_pinjaman', short_window=7, long_window=30, apply_time_dt=apply_dt)

        # perc_fdcpin_30v90d
        perc_fdcpin_30v90d = calc_period_compare(data, field_set='fdc_pinjaman', short_window=30, long_window=90, apply_time_dt=apply_dt)

        # perc_fdcpin_30v180d
        perc_fdcpin_30v180d = calc_period_compare(data, field_set='fdc_pinjaman', short_window=30, long_window=180, apply_time_dt=apply_dt)

        # perc_app_7v30d
        perc_app_7v30d = calc_period_compare(data, field_set='applist', short_window=7, long_window=30, apply_time_dt=apply_dt)

        # perc_app_15v60d
        perc_app_15v60d = calc_period_compare(data, field_set='applist', short_window=15, long_window=60, apply_time_dt=apply_dt)

        # trend_fdciq_7_15_30d
        trend_fdciq_7_15_30d = calc_trend(data, field_set='fdc_inquiry', windows=[7, 15, 30], apply_time_dt=apply_dt)

        # trend_fdciq_3_7_30d
        trend_fdciq_3_7_30d = calc_trend(data, field_set='fdc_inquiry', windows=[3, 7, 30], apply_time_dt=apply_dt)

        # trend_fdcpin_7_30_60d
        trend_fdcpin_7_30_60d = calc_trend(data, field_set='fdc_pinjaman', windows=[7, 30, 60], apply_time_dt=apply_dt)

        # trend_fdcpin_30_60_90d
        trend_fdcpin_30_60_90d = calc_trend(data, field_set='fdc_pinjaman', windows=[30, 60, 90], apply_time_dt=apply_dt)

        # trend_fdcpin_60_90_180d
        trend_fdcpin_60_90_180d = calc_trend(data, field_set='fdc_pinjaman', windows=[60, 90, 180], apply_time_dt=apply_dt)

        # trend_app_7_15_30d
        trend_app_7_15_30d = calc_trend(data, field_set='applist', windows=[7, 15, 30], apply_time_dt=apply_dt)

        # trend_app_30_60_90d
        trend_app_30_60_90d = calc_trend(data, field_set='applist', windows=[30, 60, 90], apply_time_dt=apply_dt)

        # spike_app_15d_2x0
        spike_app_15d_2x0 = calc_spike(data, field_set='applist', window_days=15, threshold=2.0, apply_time_dt=apply_dt)

        # spike_app_15d_3x0
        spike_app_15d_3x0 = calc_spike(data, field_set='applist', window_days=15, threshold=3.0, apply_time_dt=apply_dt)

        # spike_app_30d_2x0
        spike_app_30d_2x0 = calc_spike(data, field_set='applist', window_days=30, threshold=2.0, apply_time_dt=apply_dt)

        # spike_app_30d_3x0
        spike_app_30d_3x0 = calc_spike(data, field_set='applist', window_days=30, threshold=3.0, apply_time_dt=apply_dt)

        # spike_app_60d_2x0
        spike_app_60d_2x0 = calc_spike(data, field_set='applist', window_days=60, threshold=2.0, apply_time_dt=apply_dt)

        # spike_app_60d_3x0
        spike_app_60d_3x0 = calc_spike(data, field_set='applist', window_days=60, threshold=3.0, apply_time_dt=apply_dt)

        # spike_fdcpin_15d_2x0
        spike_fdcpin_15d_2x0 = calc_spike(data, field_set='fdc_pinjaman', window_days=15, threshold=2.0, apply_time_dt=apply_dt)

        # spike_fdcpin_15d_3x0
        spike_fdcpin_15d_3x0 = calc_spike(data, field_set='fdc_pinjaman', window_days=15, threshold=3.0, apply_time_dt=apply_dt)

        # spike_fdcpin_30d_2x0
        spike_fdcpin_30d_2x0 = calc_spike(data, field_set='fdc_pinjaman', window_days=30, threshold=2.0, apply_time_dt=apply_dt)

        # spike_fdcpin_30d_3x0
        spike_fdcpin_30d_3x0 = calc_spike(data, field_set='fdc_pinjaman', window_days=30, threshold=3.0, apply_time_dt=apply_dt)

        # spike_fdcpin_60d_2x0
        spike_fdcpin_60d_2x0 = calc_spike(data, field_set='fdc_pinjaman', window_days=60, threshold=2.0, apply_time_dt=apply_dt)

        # spike_fdcpin_60d_3x0
        spike_fdcpin_60d_3x0 = calc_spike(data, field_set='fdc_pinjaman', window_days=60, threshold=3.0, apply_time_dt=apply_dt)

        # pctl_salary_pop
        pctl_salary_pop = calc_percentile(value=self._get_salary_from_data(data), reference_distribution=self.ref_distributions.get('salary_distribution', []))

        # pctl_loan_amount_pop
        pctl_loan_amount_pop = calc_percentile(value=self._get_loan_amount_from_data(data), reference_distribution=self.ref_distributions.get('loan_amount_distribution', []))

        # pctl_inquiry_count_pop
        pctl_inquiry_count_pop = calc_percentile(value=self._get_inquiry_count_from_data(data), reference_distribution=self.ref_distributions.get('inquiry_count_distribution', []))

        # pctl_applist_count_pop
        pctl_applist_count_pop = calc_percentile(value=self._get_applist_count_from_data(data), reference_distribution=self.ref_distributions.get('applist_count_distribution', []))

        # dev_salary_peer
        dev_salary_peer = calc_deviation(value=self._get_salary_from_data(data), ref_mean=self.ref_distributions.get('salary_mean', 0), ref_std=self.ref_distributions.get('salary_std', 1))

        # dev_loan_amount_peer
        dev_loan_amount_peer = calc_deviation(value=self._get_loan_amount_from_data(data), ref_mean=self.ref_distributions.get('loan_amount_mean', 0), ref_std=self.ref_distributions.get('loan_amount_std', 1))

        # dev_inquiry_count_peer
        dev_inquiry_count_peer = calc_deviation(value=self._get_inquiry_count_from_data(data), ref_mean=self.ref_distributions.get('inquiry_count_mean', 0), ref_std=self.ref_distributions.get('inquiry_count_std', 1))

        # dev_applist_count_peer
        dev_applist_count_peer = calc_deviation(value=self._get_applist_count_from_data(data), ref_mean=self.ref_distributions.get('applist_count_mean', 0), ref_std=self.ref_distributions.get('applist_count_std', 1))

        # anom_app
        anom_app = calc_anomaly(feature_vector=self._get_app_install_pattern_vector(data), reference_matrix=self.ref_distributions.get('app_feature_vectors', []), method='mahalanobis')

        # anom_loan
        anom_loan = calc_anomaly(feature_vector=self._get_loan_pattern_vector(data), reference_matrix=self.ref_distributions.get('loan_feature_vectors', []), method='mahalanobis')

        # da_salary_loan_ratio
        da_salary_loan_ratio = calc_declared_vs_actual(data, declared_field='base.salary', actual_field='fdc_pinjaman.nilai_pendanaan', method='ratio')

        # da_salary_loan_gap
        da_salary_loan_gap = calc_declared_vs_actual(data, declared_field='base.salary', actual_field='fdc_pinjaman.nilai_pendanaan', method='gap')

        # da_salary_loan_abs_diff
        da_salary_loan_abs_diff = calc_declared_vs_actual(data, declared_field='base.salary', actual_field='fdc_pinjaman.nilai_pendanaan', method='abs_diff')

        # disc_salary_loan
        disc_salary_loan = calc_cross_discrepancy(data, field_pairs=[{'src': 'base', 'field': 'salary'}, {'src': 'fdc_pinjaman', 'field': 'nilai_pendanaan'}])

        # cluster_device_pkg
        cluster_device_pkg = calc_identity_cluster(data, identity_field='device_id', shared_field='packageX')

        # cluster_device_penyelenggara
        cluster_device_penyelenggara = calc_identity_cluster(data, identity_field='device_id', shared_field='id_penyelenggara')

        # ===== Derived Features (T016) =====
        # d_dens_app_7d
        d_dens_app_7d = cnt_app_7d / 7.0 if cnt_app_7d > 0 else 0.0

        # d_dens_app_15d
        d_dens_app_15d = cnt_app_15d / 15.0 if cnt_app_15d > 0 else 0.0

        # d_dens_app_30d
        d_dens_app_30d = cnt_app_30d / 30.0 if cnt_app_30d > 0 else 0.0

        # d_dens_app_60d
        d_dens_app_60d = cnt_app_60d / 60.0 if cnt_app_60d > 0 else 0.0

        # d_dens_app_90d
        d_dens_app_90d = cnt_app_90d / 90.0 if cnt_app_90d > 0 else 0.0

        # d_dens_app_180d
        d_dens_app_180d = cnt_app_180d / 180.0 if cnt_app_180d > 0 else 0.0

        # d_dens_fdcpin_7d
        d_dens_fdcpin_7d = cnt_fdcpin_7d / 7.0 if cnt_fdcpin_7d > 0 else 0.0

        # d_dens_fdcpin_15d
        d_dens_fdcpin_15d = cnt_fdcpin_15d / 15.0 if cnt_fdcpin_15d > 0 else 0.0

        # d_dens_fdcpin_30d
        d_dens_fdcpin_30d = cnt_fdcpin_30d / 30.0 if cnt_fdcpin_30d > 0 else 0.0

        # d_dens_fdcpin_60d
        d_dens_fdcpin_60d = cnt_fdcpin_60d / 60.0 if cnt_fdcpin_60d > 0 else 0.0

        # d_dens_fdcpin_90d
        d_dens_fdcpin_90d = cnt_fdcpin_90d / 90.0 if cnt_fdcpin_90d > 0 else 0.0

        # d_dens_fdcpin_180d
        d_dens_fdcpin_180d = cnt_fdcpin_180d / 180.0 if cnt_fdcpin_180d > 0 else 0.0

        # d_dens_fdciq_3d
        d_dens_fdciq_3d = cnt_fdciq_3d / 3.0 if cnt_fdciq_3d > 0 else 0.0

        # d_dens_fdciq_7d
        d_dens_fdciq_7d = cnt_fdciq_7d / 7.0 if cnt_fdciq_7d > 0 else 0.0

        # d_dens_fdciq_15d
        d_dens_fdciq_15d = cnt_fdciq_15d / 15.0 if cnt_fdciq_15d > 0 else 0.0

        # d_dens_fdciq_30d
        d_dens_fdciq_30d = cnt_fdciq_30d / 30.0 if cnt_fdciq_30d > 0 else 0.0

        # d_dens_fdciq_90d
        d_dens_fdciq_90d = cnt_fdciq_90d / 90.0 if cnt_fdciq_90d > 0 else 0.0

        # d_dens_fdciq_180d
        d_dens_fdciq_180d = cnt_fdciq_180d / 180.0 if cnt_fdciq_180d > 0 else 0.0

        # d_ratio_gambling_banking_30d
        d_ratio_gambling_banking_30d = prop_app_gambling_30d / prop_app_banking_30d if prop_app_banking_30d != 0 else 0.0

        # d_ratio_gambling_banking_90d
        d_ratio_gambling_banking_90d = prop_app_gambling_90d / prop_app_banking_90d if prop_app_banking_90d != 0 else 0.0

        # d_ratio_highrisk_banking_30d
        d_ratio_highrisk_banking_30d = prop_app_gambling_cash_loan_fintech_lending_30d / prop_app_banking_30d if prop_app_banking_30d != 0 else 0.0

        # d_ratio_highrisk_banking_90d
        d_ratio_highrisk_banking_90d = prop_app_gambling_cash_loan_fintech_lending_90d / prop_app_banking_90d if prop_app_banking_90d != 0 else 0.0

        # d_ratio_activeloan_30d
        d_ratio_activeloan_30d = cnt_fdcpin_status_pinjaman_o_30d / cnt_fdcpin_30d if cnt_fdcpin_30d != 0 else 0.0

        # d_ratio_writeoff_30d
        d_ratio_writeoff_30d = cnt_fdcpin_status_pinjaman_w_30d / cnt_fdcpin_30d if cnt_fdcpin_30d != 0 else 0.0

        # d_ratio_avg_loans_per_lender_30d
        d_ratio_avg_loans_per_lender_30d = cnt_fdcpin_30d / uniq_fdcpin_lender_30d if uniq_fdcpin_lender_30d != 0 else 0.0

        # d_ratio_avg_loans_per_lender_90d
        d_ratio_avg_loans_per_lender_90d = cnt_fdcpin_90d / uniq_fdcpin_lender_90d if uniq_fdcpin_lender_90d != 0 else 0.0

        # d_ratio_avg_amt_30d
        d_ratio_avg_amt_30d = decay_fdcpin_amt_30d_r005 / cnt_fdcpin_30d if cnt_fdcpin_30d != 0 else 0.0

        # d_ratio_avg_amt_180d
        d_ratio_avg_amt_180d = decay_fdcpin_amt_180d_r005 / cnt_fdcpin_180d if cnt_fdcpin_180d != 0 else 0.0

        # d_ratio_spending_conc_30v180
        d_ratio_spending_conc_30v180 = decay_fdcpin_amt_30d_r005 / decay_fdcpin_amt_180d_r005 if decay_fdcpin_amt_180d_r005 != 0 else 0.0

        # d_ratio_deterioration_30d
        d_ratio_deterioration_30d = prop_fdcpin_kualitas_pinjaman_3_30d / prop_fdcpin_kualitas_pinjaman_1_30d if prop_fdcpin_kualitas_pinjaman_1_30d != 0 else 0.0

        # d_ratio_kualitas5_ratio_30d
        d_ratio_kualitas5_ratio_30d = prop_fdcpin_kualitas_pinjaman_5_30d / prop_fdcpin_kualitas_pinjaman_1_30d if prop_fdcpin_kualitas_pinjaman_1_30d != 0 else 0.0

        # d_wcomb_riskexp_30d
        d_wcomb_riskexp_30d = prop_app_gambling_30d * cnt_fdcpin_status_pinjaman_o_30d

        # d_wcomb_riskexp_90d
        d_wcomb_riskexp_90d = prop_app_gambling_90d * cnt_fdcpin_status_pinjaman_o_90d

        # d_wcomb_highrisk_loan_30d
        d_wcomb_highrisk_loan_30d = prop_app_gambling_cash_loan_fintech_lending_30d * cnt_fdcpin_30d

        # d_wcomb_highrisk_loan_90d
        d_wcomb_highrisk_loan_90d = prop_app_gambling_cash_loan_fintech_lending_90d * cnt_fdcpin_90d

        # d_vel_app_7v90d
        d_vel_app_7v90d = ((cnt_app_7d / 7.0) / (cnt_app_90d / 90.0) - 1.0) if cnt_app_90d > 0 else 0.0

        # d_vel_fdcpin_7v30d
        d_vel_fdcpin_7v30d = ((cnt_fdcpin_7d / 7.0) / (cnt_fdcpin_30d / 30.0) - 1.0) if cnt_fdcpin_30d > 0 else 0.0

        # d_vel_fdcpin_15v90d
        d_vel_fdcpin_15v90d = ((cnt_fdcpin_15d / 15.0) / (cnt_fdcpin_90d / 90.0) - 1.0) if cnt_fdcpin_90d > 0 else 0.0

        # d_vel_fdcpin_7v180d
        d_vel_fdcpin_7v180d = ((cnt_fdcpin_7d / 7.0) / (cnt_fdcpin_180d / 180.0) - 1.0) if cnt_fdcpin_180d > 0 else 0.0

        # d_vel_fdciq_3v30d
        d_vel_fdciq_3v30d = ((cnt_fdciq_3d / 3.0) / (cnt_fdciq_30d / 30.0) - 1.0) if cnt_fdciq_30d > 0 else 0.0

        # d_vel_fdciq_7v90d
        d_vel_fdciq_7v90d = ((cnt_fdciq_7d / 7.0) / (cnt_fdciq_90d / 90.0) - 1.0) if cnt_fdciq_90d > 0 else 0.0

        # d_vel_fdciq_3v90d
        d_vel_fdciq_3v90d = ((cnt_fdciq_3d / 3.0) / (cnt_fdciq_90d / 90.0) - 1.0) if cnt_fdciq_90d > 0 else 0.0

        # d_vel_fdciq_15v180d
        d_vel_fdciq_15v180d = ((cnt_fdciq_15d / 15.0) / (cnt_fdciq_180d / 180.0) - 1.0) if cnt_fdciq_180d > 0 else 0.0

        # d_vel_lender_30v90d
        d_vel_lender_30v90d = ((uniq_fdcpin_lender_30d / 30.0) / (uniq_fdcpin_lender_90d / 90.0) - 1.0) if uniq_fdcpin_lender_90d > 0 else 0.0

        # d_sq_cnt_fdcpin_30d
        d_sq_cnt_fdcpin_30d = cnt_fdcpin_30d ** 2

        # d_sq_cnt_fdcpin_90d
        d_sq_cnt_fdcpin_90d = cnt_fdcpin_90d ** 2

        # d_sq_cnt_fdcpin_180d
        d_sq_cnt_fdcpin_180d = cnt_fdcpin_180d ** 2

        # d_sq_cnt_app_30d
        d_sq_cnt_app_30d = cnt_app_30d ** 2

        # d_sq_cnt_app_90d
        d_sq_cnt_app_90d = cnt_app_90d ** 2

        # d_sq_cnt_fdciq_30d
        d_sq_cnt_fdciq_30d = cnt_fdciq_30d ** 2

        # d_sq_cnt_fdciq_90d
        d_sq_cnt_fdciq_90d = cnt_fdciq_90d ** 2

        # d_sq_uniq_fdcpin_lender_30d
        d_sq_uniq_fdcpin_lender_30d = uniq_fdcpin_lender_30d ** 2

        # d_sq_uniq_fdcpin_lender_90d
        d_sq_uniq_fdcpin_lender_90d = uniq_fdcpin_lender_90d ** 2

        # d_log_cnt_fdcpin_30d
        d_log_cnt_fdcpin_30d = math.log(cnt_fdcpin_30d + 1) if cnt_fdcpin_30d >= 0 else 0.0

        # d_log_cnt_fdcpin_90d
        d_log_cnt_fdcpin_90d = math.log(cnt_fdcpin_90d + 1) if cnt_fdcpin_90d >= 0 else 0.0

        # d_log_cnt_fdcpin_180d
        d_log_cnt_fdcpin_180d = math.log(cnt_fdcpin_180d + 1) if cnt_fdcpin_180d >= 0 else 0.0

        # d_log_cnt_app_30d
        d_log_cnt_app_30d = math.log(cnt_app_30d + 1) if cnt_app_30d >= 0 else 0.0

        # d_log_cnt_app_90d
        d_log_cnt_app_90d = math.log(cnt_app_90d + 1) if cnt_app_90d >= 0 else 0.0

        # d_log_cnt_fdciq_30d
        d_log_cnt_fdciq_30d = math.log(cnt_fdciq_30d + 1) if cnt_fdciq_30d >= 0 else 0.0

        # d_log_cnt_fdciq_90d
        d_log_cnt_fdciq_90d = math.log(cnt_fdciq_90d + 1) if cnt_fdciq_90d >= 0 else 0.0

        # d_log_uniq_fdcpin_lender_30d
        d_log_uniq_fdcpin_lender_30d = math.log(uniq_fdcpin_lender_30d + 1) if uniq_fdcpin_lender_30d >= 0 else 0.0

        # d_log_uniq_fdcpin_lender_90d
        d_log_uniq_fdcpin_lender_90d = math.log(uniq_fdcpin_lender_90d + 1) if uniq_fdcpin_lender_90d >= 0 else 0.0

        # d_log_decay_fdcpin_amt_30d_r005
        d_log_decay_fdcpin_amt_30d_r005 = math.log(decay_fdcpin_amt_30d_r005 + 1) if decay_fdcpin_amt_30d_r005 >= 0 else 0.0

        # d_log_decay_fdcpin_amt_180d_r005
        d_log_decay_fdcpin_amt_180d_r005 = math.log(decay_fdcpin_amt_180d_r005 + 1) if decay_fdcpin_amt_180d_r005 >= 0 else 0.0

        return {
            'cnt_fdciq_3d': cnt_fdciq_3d,
            'cnt_fdciq_7d': cnt_fdciq_7d,
            'cnt_fdciq_15d': cnt_fdciq_15d,
            'cnt_fdciq_30d': cnt_fdciq_30d,
            'cnt_fdciq_90d': cnt_fdciq_90d,
            'cnt_fdciq_180d': cnt_fdciq_180d,
            'cnt_app_7d': cnt_app_7d,
            'cnt_app_15d': cnt_app_15d,
            'cnt_app_30d': cnt_app_30d,
            'cnt_app_60d': cnt_app_60d,
            'cnt_app_90d': cnt_app_90d,
            'cnt_app_180d': cnt_app_180d,
            'cnt_fdcpin_7d': cnt_fdcpin_7d,
            'cnt_fdcpin_15d': cnt_fdcpin_15d,
            'cnt_fdcpin_30d': cnt_fdcpin_30d,
            'cnt_fdcpin_60d': cnt_fdcpin_60d,
            'cnt_fdcpin_90d': cnt_fdcpin_90d,
            'cnt_fdcpin_180d': cnt_fdcpin_180d,
            'cnt_fdcpin_status_pinjaman_o_7d': cnt_fdcpin_status_pinjaman_o_7d,
            'cnt_fdcpin_status_pinjaman_o_15d': cnt_fdcpin_status_pinjaman_o_15d,
            'cnt_fdcpin_status_pinjaman_o_30d': cnt_fdcpin_status_pinjaman_o_30d,
            'cnt_fdcpin_status_pinjaman_o_60d': cnt_fdcpin_status_pinjaman_o_60d,
            'cnt_fdcpin_status_pinjaman_o_90d': cnt_fdcpin_status_pinjaman_o_90d,
            'cnt_fdcpin_status_pinjaman_o_180d': cnt_fdcpin_status_pinjaman_o_180d,
            'cnt_fdcpin_status_pinjaman_l_7d': cnt_fdcpin_status_pinjaman_l_7d,
            'cnt_fdcpin_status_pinjaman_l_15d': cnt_fdcpin_status_pinjaman_l_15d,
            'cnt_fdcpin_status_pinjaman_l_30d': cnt_fdcpin_status_pinjaman_l_30d,
            'cnt_fdcpin_status_pinjaman_l_60d': cnt_fdcpin_status_pinjaman_l_60d,
            'cnt_fdcpin_status_pinjaman_l_90d': cnt_fdcpin_status_pinjaman_l_90d,
            'cnt_fdcpin_status_pinjaman_l_180d': cnt_fdcpin_status_pinjaman_l_180d,
            'cnt_fdcpin_status_pinjaman_w_7d': cnt_fdcpin_status_pinjaman_w_7d,
            'cnt_fdcpin_status_pinjaman_w_15d': cnt_fdcpin_status_pinjaman_w_15d,
            'cnt_fdcpin_status_pinjaman_w_30d': cnt_fdcpin_status_pinjaman_w_30d,
            'cnt_fdcpin_status_pinjaman_w_60d': cnt_fdcpin_status_pinjaman_w_60d,
            'cnt_fdcpin_status_pinjaman_w_90d': cnt_fdcpin_status_pinjaman_w_90d,
            'cnt_fdcpin_status_pinjaman_w_180d': cnt_fdcpin_status_pinjaman_w_180d,
            'cnt_fdcpin_status_pinjaman_f_7d': cnt_fdcpin_status_pinjaman_f_7d,
            'cnt_fdcpin_status_pinjaman_f_15d': cnt_fdcpin_status_pinjaman_f_15d,
            'cnt_fdcpin_status_pinjaman_f_30d': cnt_fdcpin_status_pinjaman_f_30d,
            'cnt_fdcpin_status_pinjaman_f_60d': cnt_fdcpin_status_pinjaman_f_60d,
            'cnt_fdcpin_status_pinjaman_f_90d': cnt_fdcpin_status_pinjaman_f_90d,
            'cnt_fdcpin_status_pinjaman_f_180d': cnt_fdcpin_status_pinjaman_f_180d,
            'cnt_fdcpin_kualitas_pinjaman_1_7d': cnt_fdcpin_kualitas_pinjaman_1_7d,
            'cnt_fdcpin_kualitas_pinjaman_1_15d': cnt_fdcpin_kualitas_pinjaman_1_15d,
            'cnt_fdcpin_kualitas_pinjaman_1_30d': cnt_fdcpin_kualitas_pinjaman_1_30d,
            'cnt_fdcpin_kualitas_pinjaman_1_60d': cnt_fdcpin_kualitas_pinjaman_1_60d,
            'cnt_fdcpin_kualitas_pinjaman_1_90d': cnt_fdcpin_kualitas_pinjaman_1_90d,
            'cnt_fdcpin_kualitas_pinjaman_1_180d': cnt_fdcpin_kualitas_pinjaman_1_180d,
            'cnt_fdcpin_kualitas_pinjaman_3_7d': cnt_fdcpin_kualitas_pinjaman_3_7d,
            'cnt_fdcpin_kualitas_pinjaman_3_15d': cnt_fdcpin_kualitas_pinjaman_3_15d,
            'cnt_fdcpin_kualitas_pinjaman_3_30d': cnt_fdcpin_kualitas_pinjaman_3_30d,
            'cnt_fdcpin_kualitas_pinjaman_3_60d': cnt_fdcpin_kualitas_pinjaman_3_60d,
            'cnt_fdcpin_kualitas_pinjaman_3_90d': cnt_fdcpin_kualitas_pinjaman_3_90d,
            'cnt_fdcpin_kualitas_pinjaman_3_180d': cnt_fdcpin_kualitas_pinjaman_3_180d,
            'cnt_fdcpin_kualitas_pinjaman_5_7d': cnt_fdcpin_kualitas_pinjaman_5_7d,
            'cnt_fdcpin_kualitas_pinjaman_5_15d': cnt_fdcpin_kualitas_pinjaman_5_15d,
            'cnt_fdcpin_kualitas_pinjaman_5_30d': cnt_fdcpin_kualitas_pinjaman_5_30d,
            'cnt_fdcpin_kualitas_pinjaman_5_60d': cnt_fdcpin_kualitas_pinjaman_5_60d,
            'cnt_fdcpin_kualitas_pinjaman_5_90d': cnt_fdcpin_kualitas_pinjaman_5_90d,
            'cnt_fdcpin_kualitas_pinjaman_5_180d': cnt_fdcpin_kualitas_pinjaman_5_180d,
            'cnt_fdcpin_tipe_pinjaman_multiguna_7d': cnt_fdcpin_tipe_pinjaman_multiguna_7d,
            'cnt_fdcpin_tipe_pinjaman_multiguna_15d': cnt_fdcpin_tipe_pinjaman_multiguna_15d,
            'cnt_fdcpin_tipe_pinjaman_multiguna_30d': cnt_fdcpin_tipe_pinjaman_multiguna_30d,
            'cnt_fdcpin_tipe_pinjaman_multiguna_60d': cnt_fdcpin_tipe_pinjaman_multiguna_60d,
            'cnt_fdcpin_tipe_pinjaman_multiguna_90d': cnt_fdcpin_tipe_pinjaman_multiguna_90d,
            'cnt_fdcpin_tipe_pinjaman_multiguna_180d': cnt_fdcpin_tipe_pinjaman_multiguna_180d,
            'cnt_fdcpin_tipe_pinjaman_produktif_7d': cnt_fdcpin_tipe_pinjaman_produktif_7d,
            'cnt_fdcpin_tipe_pinjaman_produktif_15d': cnt_fdcpin_tipe_pinjaman_produktif_15d,
            'cnt_fdcpin_tipe_pinjaman_produktif_30d': cnt_fdcpin_tipe_pinjaman_produktif_30d,
            'cnt_fdcpin_tipe_pinjaman_produktif_60d': cnt_fdcpin_tipe_pinjaman_produktif_60d,
            'cnt_fdcpin_tipe_pinjaman_produktif_90d': cnt_fdcpin_tipe_pinjaman_produktif_90d,
            'cnt_fdcpin_tipe_pinjaman_produktif_180d': cnt_fdcpin_tipe_pinjaman_produktif_180d,
            'cnt_fdcpin_pendanaan_syariah_true_7d': cnt_fdcpin_pendanaan_syariah_true_7d,
            'cnt_fdcpin_pendanaan_syariah_true_15d': cnt_fdcpin_pendanaan_syariah_true_15d,
            'cnt_fdcpin_pendanaan_syariah_true_30d': cnt_fdcpin_pendanaan_syariah_true_30d,
            'cnt_fdcpin_pendanaan_syariah_true_60d': cnt_fdcpin_pendanaan_syariah_true_60d,
            'cnt_fdcpin_pendanaan_syariah_true_90d': cnt_fdcpin_pendanaan_syariah_true_90d,
            'cnt_fdcpin_pendanaan_syariah_true_180d': cnt_fdcpin_pendanaan_syariah_true_180d,
            'cnt_fdcpin_pendanaan_syariah_false_7d': cnt_fdcpin_pendanaan_syariah_false_7d,
            'cnt_fdcpin_pendanaan_syariah_false_15d': cnt_fdcpin_pendanaan_syariah_false_15d,
            'cnt_fdcpin_pendanaan_syariah_false_30d': cnt_fdcpin_pendanaan_syariah_false_30d,
            'cnt_fdcpin_pendanaan_syariah_false_60d': cnt_fdcpin_pendanaan_syariah_false_60d,
            'cnt_fdcpin_pendanaan_syariah_false_90d': cnt_fdcpin_pendanaan_syariah_false_90d,
            'cnt_fdcpin_pendanaan_syariah_false_180d': cnt_fdcpin_pendanaan_syariah_false_180d,
            'uniq_fdciq_hitby_7d': uniq_fdciq_hitby_7d,
            'uniq_fdciq_hitby_15d': uniq_fdciq_hitby_15d,
            'uniq_fdciq_hitby_30d': uniq_fdciq_hitby_30d,
            'uniq_fdciq_hitby_60d': uniq_fdciq_hitby_60d,
            'uniq_fdciq_hitby_90d': uniq_fdciq_hitby_90d,
            'uniq_fdciq_hitby_180d': uniq_fdciq_hitby_180d,
            'uniq_fdcpin_lender_30d': uniq_fdcpin_lender_30d,
            'uniq_fdcpin_lender_60d': uniq_fdcpin_lender_60d,
            'uniq_fdcpin_lender_90d': uniq_fdcpin_lender_90d,
            'uniq_fdcpin_lender_180d': uniq_fdcpin_lender_180d,
            'uniq_fdcpin_loan_type_30d': uniq_fdcpin_loan_type_30d,
            'uniq_fdcpin_loan_type_60d': uniq_fdcpin_loan_type_60d,
            'uniq_fdcpin_loan_type_90d': uniq_fdcpin_loan_type_90d,
            'uniq_fdcpin_loan_type_180d': uniq_fdcpin_loan_type_180d,
            'uniq_fdcpin_loan_status_30d': uniq_fdcpin_loan_status_30d,
            'uniq_fdcpin_loan_status_60d': uniq_fdcpin_loan_status_60d,
            'uniq_fdcpin_loan_status_90d': uniq_fdcpin_loan_status_90d,
            'uniq_fdcpin_loan_status_180d': uniq_fdcpin_loan_status_180d,
            'decay_fdcpin_amt_30d_r005': decay_fdcpin_amt_30d_r005,
            'decay_fdcpin_amt_60d_r005': decay_fdcpin_amt_60d_r005,
            'decay_fdcpin_amt_90d_r005': decay_fdcpin_amt_90d_r005,
            'decay_fdcpin_amt_180d_r005': decay_fdcpin_amt_180d_r005,
            'decay_fdcpin_amt_30d_r002': decay_fdcpin_amt_30d_r002,
            'decay_fdcpin_amt_60d_r002': decay_fdcpin_amt_60d_r002,
            'decay_fdcpin_amt_90d_r002': decay_fdcpin_amt_90d_r002,
            'decay_fdcpin_amt_180d_r002': decay_fdcpin_amt_180d_r002,
            'decay_fdcpin_amt_30d_r01': decay_fdcpin_amt_30d_r01,
            'decay_fdcpin_amt_60d_r01': decay_fdcpin_amt_60d_r01,
            'decay_fdcpin_amt_90d_r01': decay_fdcpin_amt_90d_r01,
            'decay_fdcpin_amt_180d_r01': decay_fdcpin_amt_180d_r01,
            'decay_fdcpin_amt_30d_r05': decay_fdcpin_amt_30d_r05,
            'decay_fdcpin_amt_60d_r05': decay_fdcpin_amt_60d_r05,
            'decay_fdcpin_amt_90d_r05': decay_fdcpin_amt_90d_r05,
            'decay_fdcpin_amt_180d_r05': decay_fdcpin_amt_180d_r05,
            'prop_app_gambling_7d': prop_app_gambling_7d,
            'prop_app_gambling_30d': prop_app_gambling_30d,
            'prop_app_gambling_60d': prop_app_gambling_60d,
            'prop_app_gambling_90d': prop_app_gambling_90d,
            'prop_app_cash_loan_7d': prop_app_cash_loan_7d,
            'prop_app_cash_loan_30d': prop_app_cash_loan_30d,
            'prop_app_cash_loan_60d': prop_app_cash_loan_60d,
            'prop_app_cash_loan_90d': prop_app_cash_loan_90d,
            'prop_app_fintech_lending_7d': prop_app_fintech_lending_7d,
            'prop_app_fintech_lending_30d': prop_app_fintech_lending_30d,
            'prop_app_fintech_lending_60d': prop_app_fintech_lending_60d,
            'prop_app_fintech_lending_90d': prop_app_fintech_lending_90d,
            'prop_app_fake_gps_7d': prop_app_fake_gps_7d,
            'prop_app_fake_gps_30d': prop_app_fake_gps_30d,
            'prop_app_fake_gps_60d': prop_app_fake_gps_60d,
            'prop_app_fake_gps_90d': prop_app_fake_gps_90d,
            'prop_app_clone_app_7d': prop_app_clone_app_7d,
            'prop_app_clone_app_30d': prop_app_clone_app_30d,
            'prop_app_clone_app_60d': prop_app_clone_app_60d,
            'prop_app_clone_app_90d': prop_app_clone_app_90d,
            'prop_app_banking_7d': prop_app_banking_7d,
            'prop_app_banking_30d': prop_app_banking_30d,
            'prop_app_banking_60d': prop_app_banking_60d,
            'prop_app_banking_90d': prop_app_banking_90d,
            'prop_app_ewallet_7d': prop_app_ewallet_7d,
            'prop_app_ewallet_30d': prop_app_ewallet_30d,
            'prop_app_ewallet_60d': prop_app_ewallet_60d,
            'prop_app_ewallet_90d': prop_app_ewallet_90d,
            'prop_app_cash_loan_fintech_lending_7d': prop_app_cash_loan_fintech_lending_7d,
            'prop_app_cash_loan_fintech_lending_30d': prop_app_cash_loan_fintech_lending_30d,
            'prop_app_cash_loan_fintech_lending_60d': prop_app_cash_loan_fintech_lending_60d,
            'prop_app_cash_loan_fintech_lending_90d': prop_app_cash_loan_fintech_lending_90d,
            'prop_app_gambling_cash_loan_fintech_lending_7d': prop_app_gambling_cash_loan_fintech_lending_7d,
            'prop_app_gambling_cash_loan_fintech_lending_30d': prop_app_gambling_cash_loan_fintech_lending_30d,
            'prop_app_gambling_cash_loan_fintech_lending_60d': prop_app_gambling_cash_loan_fintech_lending_60d,
            'prop_app_gambling_cash_loan_fintech_lending_90d': prop_app_gambling_cash_loan_fintech_lending_90d,
            'prop_app_shopping_food_delivery_7d': prop_app_shopping_food_delivery_7d,
            'prop_app_shopping_food_delivery_30d': prop_app_shopping_food_delivery_30d,
            'prop_app_shopping_food_delivery_60d': prop_app_shopping_food_delivery_60d,
            'prop_app_shopping_food_delivery_90d': prop_app_shopping_food_delivery_90d,
            'prop_fdcpin_kualitas_pinjaman_1_30d': prop_fdcpin_kualitas_pinjaman_1_30d,
            'prop_fdcpin_kualitas_pinjaman_1_60d': prop_fdcpin_kualitas_pinjaman_1_60d,
            'prop_fdcpin_kualitas_pinjaman_1_90d': prop_fdcpin_kualitas_pinjaman_1_90d,
            'prop_fdcpin_kualitas_pinjaman_1_180d': prop_fdcpin_kualitas_pinjaman_1_180d,
            'prop_fdcpin_kualitas_pinjaman_3_30d': prop_fdcpin_kualitas_pinjaman_3_30d,
            'prop_fdcpin_kualitas_pinjaman_3_60d': prop_fdcpin_kualitas_pinjaman_3_60d,
            'prop_fdcpin_kualitas_pinjaman_3_90d': prop_fdcpin_kualitas_pinjaman_3_90d,
            'prop_fdcpin_kualitas_pinjaman_3_180d': prop_fdcpin_kualitas_pinjaman_3_180d,
            'prop_fdcpin_kualitas_pinjaman_5_30d': prop_fdcpin_kualitas_pinjaman_5_30d,
            'prop_fdcpin_kualitas_pinjaman_5_60d': prop_fdcpin_kualitas_pinjaman_5_60d,
            'prop_fdcpin_kualitas_pinjaman_5_90d': prop_fdcpin_kualitas_pinjaman_5_90d,
            'prop_fdcpin_kualitas_pinjaman_5_180d': prop_fdcpin_kualitas_pinjaman_5_180d,
            'prop_fdcpin_status_pinjaman_o_30d': prop_fdcpin_status_pinjaman_o_30d,
            'prop_fdcpin_status_pinjaman_o_60d': prop_fdcpin_status_pinjaman_o_60d,
            'prop_fdcpin_status_pinjaman_o_90d': prop_fdcpin_status_pinjaman_o_90d,
            'prop_fdcpin_status_pinjaman_o_180d': prop_fdcpin_status_pinjaman_o_180d,
            'prop_fdcpin_status_pinjaman_l_30d': prop_fdcpin_status_pinjaman_l_30d,
            'prop_fdcpin_status_pinjaman_l_60d': prop_fdcpin_status_pinjaman_l_60d,
            'prop_fdcpin_status_pinjaman_l_90d': prop_fdcpin_status_pinjaman_l_90d,
            'prop_fdcpin_status_pinjaman_l_180d': prop_fdcpin_status_pinjaman_l_180d,
            'prop_fdcpin_tipe_pinjaman_multiguna_30d': prop_fdcpin_tipe_pinjaman_multiguna_30d,
            'prop_fdcpin_tipe_pinjaman_multiguna_60d': prop_fdcpin_tipe_pinjaman_multiguna_60d,
            'prop_fdcpin_tipe_pinjaman_multiguna_90d': prop_fdcpin_tipe_pinjaman_multiguna_90d,
            'prop_fdcpin_tipe_pinjaman_multiguna_180d': prop_fdcpin_tipe_pinjaman_multiguna_180d,
            'prop_fdcpin_tipe_pinjaman_produktif_30d': prop_fdcpin_tipe_pinjaman_produktif_30d,
            'prop_fdcpin_tipe_pinjaman_produktif_60d': prop_fdcpin_tipe_pinjaman_produktif_60d,
            'prop_fdcpin_tipe_pinjaman_produktif_90d': prop_fdcpin_tipe_pinjaman_produktif_90d,
            'prop_fdcpin_tipe_pinjaman_produktif_180d': prop_fdcpin_tipe_pinjaman_produktif_180d,
            'prop_fdcpin_pendanaan_syariah_true_30d': prop_fdcpin_pendanaan_syariah_true_30d,
            'prop_fdcpin_pendanaan_syariah_true_60d': prop_fdcpin_pendanaan_syariah_true_60d,
            'prop_fdcpin_pendanaan_syariah_true_90d': prop_fdcpin_pendanaan_syariah_true_90d,
            'prop_fdcpin_pendanaan_syariah_true_180d': prop_fdcpin_pendanaan_syariah_true_180d,
            'prop_fdcpin_pendanaan_syariah_false_30d': prop_fdcpin_pendanaan_syariah_false_30d,
            'prop_fdcpin_pendanaan_syariah_false_60d': prop_fdcpin_pendanaan_syariah_false_60d,
            'prop_fdcpin_pendanaan_syariah_false_90d': prop_fdcpin_pendanaan_syariah_false_90d,
            'prop_fdcpin_pendanaan_syariah_false_180d': prop_fdcpin_pendanaan_syariah_false_180d,
            'conc_fdcpin_penyelenggara_gini_30d': conc_fdcpin_penyelenggara_gini_30d,
            'conc_fdcpin_penyelenggara_gini_60d': conc_fdcpin_penyelenggara_gini_60d,
            'conc_fdcpin_penyelenggara_gini_90d': conc_fdcpin_penyelenggara_gini_90d,
            'conc_fdcpin_penyelenggara_gini_180d': conc_fdcpin_penyelenggara_gini_180d,
            'conc_fdcpin_pinjaman_gini_30d': conc_fdcpin_pinjaman_gini_30d,
            'conc_fdcpin_pinjaman_gini_60d': conc_fdcpin_pinjaman_gini_60d,
            'conc_fdcpin_pinjaman_gini_90d': conc_fdcpin_pinjaman_gini_90d,
            'conc_fdcpin_pinjaman_gini_180d': conc_fdcpin_pinjaman_gini_180d,
            'conc_fdcpin_penyelenggara_entropy_30d': conc_fdcpin_penyelenggara_entropy_30d,
            'conc_fdcpin_penyelenggara_entropy_60d': conc_fdcpin_penyelenggara_entropy_60d,
            'conc_fdcpin_penyelenggara_entropy_90d': conc_fdcpin_penyelenggara_entropy_90d,
            'conc_fdcpin_penyelenggara_entropy_180d': conc_fdcpin_penyelenggara_entropy_180d,
            'conc_fdcpin_pinjaman_entropy_30d': conc_fdcpin_pinjaman_entropy_30d,
            'conc_fdcpin_pinjaman_entropy_60d': conc_fdcpin_pinjaman_entropy_60d,
            'conc_fdcpin_pinjaman_entropy_90d': conc_fdcpin_pinjaman_entropy_90d,
            'conc_fdcpin_pinjaman_entropy_180d': conc_fdcpin_pinjaman_entropy_180d,
            'conc_fdcpin_penyelenggara_cv_30d': conc_fdcpin_penyelenggara_cv_30d,
            'conc_fdcpin_penyelenggara_cv_60d': conc_fdcpin_penyelenggara_cv_60d,
            'conc_fdcpin_penyelenggara_cv_90d': conc_fdcpin_penyelenggara_cv_90d,
            'conc_fdcpin_penyelenggara_cv_180d': conc_fdcpin_penyelenggara_cv_180d,
            'conc_fdcpin_pinjaman_cv_30d': conc_fdcpin_pinjaman_cv_30d,
            'conc_fdcpin_pinjaman_cv_60d': conc_fdcpin_pinjaman_cv_60d,
            'conc_fdcpin_pinjaman_cv_90d': conc_fdcpin_pinjaman_cv_90d,
            'conc_fdcpin_pinjaman_cv_180d': conc_fdcpin_pinjaman_cv_180d,
            'conc_app_cat_entropy_30d': conc_app_cat_entropy_30d,
            'conc_app_cat_entropy_60d': conc_app_cat_entropy_60d,
            'conc_app_cat_entropy_90d': conc_app_cat_entropy_90d,
            'conc_app_cat_gini_30d': conc_app_cat_gini_30d,
            'conc_app_cat_gini_60d': conc_app_cat_gini_60d,
            'conc_app_cat_gini_90d': conc_app_cat_gini_90d,
            'ovlap_app_fdc_7d': ovlap_app_fdc_7d,
            'ovlap_app_fdc_30d': ovlap_app_fdc_30d,
            'ovlap_app_fdc_60d': ovlap_app_fdc_60d,
            'ovlap_app_fdc_90d': ovlap_app_fdc_90d,
            'perc_fdciq_3v7d': perc_fdciq_3v7d,
            'perc_fdciq_7v30d': perc_fdciq_7v30d,
            'perc_fdciq_15v90d': perc_fdciq_15v90d,
            'perc_fdcpin_7v30d': perc_fdcpin_7v30d,
            'perc_fdcpin_30v90d': perc_fdcpin_30v90d,
            'perc_fdcpin_30v180d': perc_fdcpin_30v180d,
            'perc_app_7v30d': perc_app_7v30d,
            'perc_app_15v60d': perc_app_15v60d,
            'trend_fdciq_7_15_30d': trend_fdciq_7_15_30d,
            'trend_fdciq_3_7_30d': trend_fdciq_3_7_30d,
            'trend_fdcpin_7_30_60d': trend_fdcpin_7_30_60d,
            'trend_fdcpin_30_60_90d': trend_fdcpin_30_60_90d,
            'trend_fdcpin_60_90_180d': trend_fdcpin_60_90_180d,
            'trend_app_7_15_30d': trend_app_7_15_30d,
            'trend_app_30_60_90d': trend_app_30_60_90d,
            'spike_app_15d_2x0': spike_app_15d_2x0,
            'spike_app_15d_3x0': spike_app_15d_3x0,
            'spike_app_30d_2x0': spike_app_30d_2x0,
            'spike_app_30d_3x0': spike_app_30d_3x0,
            'spike_app_60d_2x0': spike_app_60d_2x0,
            'spike_app_60d_3x0': spike_app_60d_3x0,
            'spike_fdcpin_15d_2x0': spike_fdcpin_15d_2x0,
            'spike_fdcpin_15d_3x0': spike_fdcpin_15d_3x0,
            'spike_fdcpin_30d_2x0': spike_fdcpin_30d_2x0,
            'spike_fdcpin_30d_3x0': spike_fdcpin_30d_3x0,
            'spike_fdcpin_60d_2x0': spike_fdcpin_60d_2x0,
            'spike_fdcpin_60d_3x0': spike_fdcpin_60d_3x0,
            'pctl_salary_pop': pctl_salary_pop,
            'pctl_loan_amount_pop': pctl_loan_amount_pop,
            'pctl_inquiry_count_pop': pctl_inquiry_count_pop,
            'pctl_applist_count_pop': pctl_applist_count_pop,
            'dev_salary_peer': dev_salary_peer,
            'dev_loan_amount_peer': dev_loan_amount_peer,
            'dev_inquiry_count_peer': dev_inquiry_count_peer,
            'dev_applist_count_peer': dev_applist_count_peer,
            'anom_app': anom_app,
            'anom_loan': anom_loan,
            'da_salary_loan_ratio': da_salary_loan_ratio,
            'da_salary_loan_gap': da_salary_loan_gap,
            'da_salary_loan_abs_diff': da_salary_loan_abs_diff,
            'disc_salary_loan': disc_salary_loan,
            'cluster_device_pkg': cluster_device_pkg,
            'cluster_device_penyelenggara': cluster_device_penyelenggara,
            'd_dens_app_7d': d_dens_app_7d,
            'd_dens_app_15d': d_dens_app_15d,
            'd_dens_app_30d': d_dens_app_30d,
            'd_dens_app_60d': d_dens_app_60d,
            'd_dens_app_90d': d_dens_app_90d,
            'd_dens_app_180d': d_dens_app_180d,
            'd_dens_fdcpin_7d': d_dens_fdcpin_7d,
            'd_dens_fdcpin_15d': d_dens_fdcpin_15d,
            'd_dens_fdcpin_30d': d_dens_fdcpin_30d,
            'd_dens_fdcpin_60d': d_dens_fdcpin_60d,
            'd_dens_fdcpin_90d': d_dens_fdcpin_90d,
            'd_dens_fdcpin_180d': d_dens_fdcpin_180d,
            'd_dens_fdciq_3d': d_dens_fdciq_3d,
            'd_dens_fdciq_7d': d_dens_fdciq_7d,
            'd_dens_fdciq_15d': d_dens_fdciq_15d,
            'd_dens_fdciq_30d': d_dens_fdciq_30d,
            'd_dens_fdciq_90d': d_dens_fdciq_90d,
            'd_dens_fdciq_180d': d_dens_fdciq_180d,
            'd_ratio_gambling_banking_30d': d_ratio_gambling_banking_30d,
            'd_ratio_gambling_banking_90d': d_ratio_gambling_banking_90d,
            'd_ratio_highrisk_banking_30d': d_ratio_highrisk_banking_30d,
            'd_ratio_highrisk_banking_90d': d_ratio_highrisk_banking_90d,
            'd_ratio_activeloan_30d': d_ratio_activeloan_30d,
            'd_ratio_writeoff_30d': d_ratio_writeoff_30d,
            'd_ratio_avg_loans_per_lender_30d': d_ratio_avg_loans_per_lender_30d,
            'd_ratio_avg_loans_per_lender_90d': d_ratio_avg_loans_per_lender_90d,
            'd_ratio_avg_amt_30d': d_ratio_avg_amt_30d,
            'd_ratio_avg_amt_180d': d_ratio_avg_amt_180d,
            'd_ratio_spending_conc_30v180': d_ratio_spending_conc_30v180,
            'd_ratio_deterioration_30d': d_ratio_deterioration_30d,
            'd_ratio_kualitas5_ratio_30d': d_ratio_kualitas5_ratio_30d,
            'd_wcomb_riskexp_30d': d_wcomb_riskexp_30d,
            'd_wcomb_riskexp_90d': d_wcomb_riskexp_90d,
            'd_wcomb_highrisk_loan_30d': d_wcomb_highrisk_loan_30d,
            'd_wcomb_highrisk_loan_90d': d_wcomb_highrisk_loan_90d,
            'd_vel_app_7v90d': d_vel_app_7v90d,
            'd_vel_fdcpin_7v30d': d_vel_fdcpin_7v30d,
            'd_vel_fdcpin_15v90d': d_vel_fdcpin_15v90d,
            'd_vel_fdcpin_7v180d': d_vel_fdcpin_7v180d,
            'd_vel_fdciq_3v30d': d_vel_fdciq_3v30d,
            'd_vel_fdciq_7v90d': d_vel_fdciq_7v90d,
            'd_vel_fdciq_3v90d': d_vel_fdciq_3v90d,
            'd_vel_fdciq_15v180d': d_vel_fdciq_15v180d,
            'd_vel_lender_30v90d': d_vel_lender_30v90d,
            'd_sq_cnt_fdcpin_30d': d_sq_cnt_fdcpin_30d,
            'd_sq_cnt_fdcpin_90d': d_sq_cnt_fdcpin_90d,
            'd_sq_cnt_fdcpin_180d': d_sq_cnt_fdcpin_180d,
            'd_sq_cnt_app_30d': d_sq_cnt_app_30d,
            'd_sq_cnt_app_90d': d_sq_cnt_app_90d,
            'd_sq_cnt_fdciq_30d': d_sq_cnt_fdciq_30d,
            'd_sq_cnt_fdciq_90d': d_sq_cnt_fdciq_90d,
            'd_sq_uniq_fdcpin_lender_30d': d_sq_uniq_fdcpin_lender_30d,
            'd_sq_uniq_fdcpin_lender_90d': d_sq_uniq_fdcpin_lender_90d,
            'd_log_cnt_fdcpin_30d': d_log_cnt_fdcpin_30d,
            'd_log_cnt_fdcpin_90d': d_log_cnt_fdcpin_90d,
            'd_log_cnt_fdcpin_180d': d_log_cnt_fdcpin_180d,
            'd_log_cnt_app_30d': d_log_cnt_app_30d,
            'd_log_cnt_app_90d': d_log_cnt_app_90d,
            'd_log_cnt_fdciq_30d': d_log_cnt_fdciq_30d,
            'd_log_cnt_fdciq_90d': d_log_cnt_fdciq_90d,
            'd_log_uniq_fdcpin_lender_30d': d_log_uniq_fdcpin_lender_30d,
            'd_log_uniq_fdcpin_lender_90d': d_log_uniq_fdcpin_lender_90d,
            'd_log_decay_fdcpin_amt_30d_r005': d_log_decay_fdcpin_amt_30d_r005,
            'd_log_decay_fdcpin_amt_180d_r005': d_log_decay_fdcpin_amt_180d_r005
        }